# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param bd.ForceAppCoreUpgrade 1
set_param general.maxThreads 1
set_param hd.Visual 0
set_param project.loadTopLevelOOCConstrs 1
create_project -in_memory -part xc7z020clg484-1
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.cache/wt [current_project]
set_property parent.project_path /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths {
  /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/iprepo/repo
  /toolsViv/Xilinx/SDx/2018.3/data/ip/xilinx
  /toolsViv/Xilinx/SDx/2018.3/data/cache/xilinx
  /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/.local/dsa/ipcache
  /toolsViv/Xilinx/SDx/2018.3/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/ip_cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/imports/hdl/zed_wrapper.v
add_files /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/zed.bd
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_ps7_0/zed_ps7_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_clk_wiz_0_0/zed_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_clk_wiz_0_0/zed_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_clk_wiz_0_0/zed_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_0_0/zed_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_0_0/zed_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_0_0/zed_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_1_0/zed_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_1_0/zed_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_1_0/zed_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_2_0/zed_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_2_0/zed_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_2_0/zed_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_4_0/zed_proc_sys_reset_4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_4_0/zed_proc_sys_reset_4_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_4_0/zed_proc_sys_reset_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_5_0/zed_proc_sys_reset_5_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_5_0/zed_proc_sys_reset_5_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_5_0/zed_proc_sys_reset_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_0_0/zed_dm_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_0_0/zed_dm_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_0_0/zed_dm_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_1_0/zed_dm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_1_0/zed_dm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_1_0/zed_dm_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_2_0/zed_dm_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_2_0/zed_dm_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_dm_2_0/zed_dm_2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_myFuncAccel_1_0/constraints/a0_myFuncAccel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_xbar_0/zed_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_xbar_1/zed_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_axis_dwc_dm_0_tx_0_0/zed_axis_dwc_dm_0_tx_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_axis_dwc_dm_1_tx_0_0/zed_axis_dwc_dm_1_tx_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_axis_dwc_dm_2_rx_0_0/zed_axis_dwc_dm_2_rx_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s00_regslice_0/zed_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s00_regslice_0/zed_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s00_data_fifo_0/zed_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_auto_pc_0/zed_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m00_regslice_0/zed_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m00_regslice_0/zed_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m01_regslice_0/zed_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m01_regslice_0/zed_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m02_regslice_0/zed_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m02_regslice_0/zed_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m03_regslice_0/zed_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m03_regslice_0/zed_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s00_regslice_1/zed_s00_regslice_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s00_regslice_1/zed_s00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s00_data_fifo_1/zed_s00_data_fifo_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s01_regslice_0/zed_s01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s01_regslice_0/zed_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s01_data_fifo_0/zed_s01_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s02_regslice_0/zed_s02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s02_regslice_0/zed_s02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_s02_data_fifo_0/zed_s02_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m00_data_fifo_0/zed_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m00_regslice_1/zed_m00_regslice_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_m00_regslice_1/zed_m00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_auto_pc_1/zed_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/zed_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/output/zed_ooc_copy.xdc
set_property used_in_implementation false [get_files /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/output/zed_ooc_copy.xdc]
set_property processing_order EARLY [get_files /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/output/zed_ooc_copy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top zed_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zed_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zed_wrapper_utilization_synth.rpt -pb zed_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
