// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "a0_myFuncAccel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic a0_myFuncAccel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> a0_myFuncAccel::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_logic a0_myFuncAccel::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<2> a0_myFuncAccel::ap_const_lv2_0 = "00";
const sc_lv<2> a0_myFuncAccel::ap_const_lv2_1 = "1";
const bool a0_myFuncAccel::ap_const_boolean_1 = true;

a0_myFuncAccel::a0_myFuncAccel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Block_codeRepl49_pro_U0 = new a0_Block_codeRepl49_pro("Block_codeRepl49_pro_U0");
    Block_codeRepl49_pro_U0->ap_clk(ap_clk);
    Block_codeRepl49_pro_U0->ap_rst(ap_rst_n_inv);
    Block_codeRepl49_pro_U0->ap_start(Block_codeRepl49_pro_U0_ap_start);
    Block_codeRepl49_pro_U0->ap_done(Block_codeRepl49_pro_U0_ap_done);
    Block_codeRepl49_pro_U0->ap_continue(Block_codeRepl49_pro_U0_ap_continue);
    Block_codeRepl49_pro_U0->ap_idle(Block_codeRepl49_pro_U0_ap_idle);
    Block_codeRepl49_pro_U0->ap_ready(Block_codeRepl49_pro_U0_ap_ready);
    Block_codeRepl49_pro_U0->data0_dout(data0_dout);
    Block_codeRepl49_pro_U0->data0_empty_n(data0_empty_n);
    Block_codeRepl49_pro_U0->data0_read(Block_codeRepl49_pro_U0_data0_read);
    Block_codeRepl49_pro_U0->size(size);
    Block_codeRepl49_pro_U0->threshold(threshold);
    Block_codeRepl49_pro_U0->size_out_din(Block_codeRepl49_pro_U0_size_out_din);
    Block_codeRepl49_pro_U0->size_out_full_n(size_c_full_n);
    Block_codeRepl49_pro_U0->size_out_write(Block_codeRepl49_pro_U0_size_out_write);
    Block_codeRepl49_pro_U0->threshold_out_din(Block_codeRepl49_pro_U0_threshold_out_din);
    Block_codeRepl49_pro_U0->threshold_out_full_n(threshold_c_full_n);
    Block_codeRepl49_pro_U0->threshold_out_write(Block_codeRepl49_pro_U0_threshold_out_write);
    Block_codeRepl49_pro_U0->ap_return_0(Block_codeRepl49_pro_U0_ap_return_0);
    Block_codeRepl49_pro_U0->ap_return_1(Block_codeRepl49_pro_U0_ap_return_1);
    Block_codeRepl49_pro_U0->ap_return_2(Block_codeRepl49_pro_U0_ap_return_2);
    Block_codeRepl49_pro_U0->ap_return_3(Block_codeRepl49_pro_U0_ap_return_3);
    Block_codeRepl49_pro_U0->ap_return_4(Block_codeRepl49_pro_U0_ap_return_4);
    Block_codeRepl49_pro_U0->ap_return_5(Block_codeRepl49_pro_U0_ap_return_5);
    Block_codeRepl49_pro_U0->ap_return_6(Block_codeRepl49_pro_U0_ap_return_6);
    Block_codeRepl49_pro_U0->ap_return_7(Block_codeRepl49_pro_U0_ap_return_7);
    Block_codeRepl49_pro_U0->ap_return_8(Block_codeRepl49_pro_U0_ap_return_8);
    Block_codeRepl49_pro_U0->ap_return_9(Block_codeRepl49_pro_U0_ap_return_9);
    Block_codeRepl49_pro_U0->ap_return_10(Block_codeRepl49_pro_U0_ap_return_10);
    Block_codeRepl49_pro_U0->ap_return_11(Block_codeRepl49_pro_U0_ap_return_11);
    Block_codeRepl49_pro_U0->ap_return_12(Block_codeRepl49_pro_U0_ap_return_12);
    Block_codeRepl49_pro_U0->ap_return_13(Block_codeRepl49_pro_U0_ap_return_13);
    Block_codeRepl49_pro_U0->ap_return_14(Block_codeRepl49_pro_U0_ap_return_14);
    Block_codeRepl49_pro_U0->ap_return_15(Block_codeRepl49_pro_U0_ap_return_15);
    Loop_sizeLoop_proc_U0 = new a0_Loop_sizeLoop_proc("Loop_sizeLoop_proc_U0");
    Loop_sizeLoop_proc_U0->ap_clk(ap_clk);
    Loop_sizeLoop_proc_U0->ap_rst(ap_rst_n_inv);
    Loop_sizeLoop_proc_U0->ap_start(Loop_sizeLoop_proc_U0_ap_start);
    Loop_sizeLoop_proc_U0->ap_done(Loop_sizeLoop_proc_U0_ap_done);
    Loop_sizeLoop_proc_U0->ap_continue(Loop_sizeLoop_proc_U0_ap_continue);
    Loop_sizeLoop_proc_U0->ap_idle(Loop_sizeLoop_proc_U0_ap_idle);
    Loop_sizeLoop_proc_U0->ap_ready(Loop_sizeLoop_proc_U0_ap_ready);
    Loop_sizeLoop_proc_U0->size_dout(size_c_dout);
    Loop_sizeLoop_proc_U0->size_empty_n(size_c_empty_n);
    Loop_sizeLoop_proc_U0->size_read(Loop_sizeLoop_proc_U0_size_read);
    Loop_sizeLoop_proc_U0->data1_dout(data1_dout);
    Loop_sizeLoop_proc_U0->data1_empty_n(data1_empty_n);
    Loop_sizeLoop_proc_U0->data1_read(Loop_sizeLoop_proc_U0_data1_read);
    Loop_sizeLoop_proc_U0->p_read(data0_load_loc_chann_dout);
    Loop_sizeLoop_proc_U0->p_read1(data0_load_1_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read2(data0_load_2_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read3(data0_load_3_loc_cha_dout);
    Loop_sizeLoop_proc_U0->threshold_dout(threshold_c_dout);
    Loop_sizeLoop_proc_U0->threshold_empty_n(threshold_c_empty_n);
    Loop_sizeLoop_proc_U0->threshold_read(Loop_sizeLoop_proc_U0_threshold_read);
    Loop_sizeLoop_proc_U0->p_read4(data0_load_4_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read5(data0_load_5_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read6(data0_load_6_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read7(data0_load_7_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read8(data0_load_8_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read9(data0_load_9_loc_cha_dout);
    Loop_sizeLoop_proc_U0->p_read10(data0_load_10_loc_ch_dout);
    Loop_sizeLoop_proc_U0->p_read11(data0_load_11_loc_ch_dout);
    Loop_sizeLoop_proc_U0->p_read12(data0_load_12_loc_ch_dout);
    Loop_sizeLoop_proc_U0->p_read13(data0_load_13_loc_ch_dout);
    Loop_sizeLoop_proc_U0->p_read14(data0_load_14_loc_ch_dout);
    Loop_sizeLoop_proc_U0->p_read15(data0_load_15_loc_ch_dout);
    Loop_sizeLoop_proc_U0->data2_din(Loop_sizeLoop_proc_U0_data2_din);
    Loop_sizeLoop_proc_U0->data2_full_n(data2_full_n);
    Loop_sizeLoop_proc_U0->data2_write(Loop_sizeLoop_proc_U0_data2_write);
    size_c_U = new a0_fifo_w32_d2_A("size_c_U");
    size_c_U->clk(ap_clk);
    size_c_U->reset(ap_rst_n_inv);
    size_c_U->if_read_ce(ap_var_for_const0);
    size_c_U->if_write_ce(ap_var_for_const0);
    size_c_U->if_din(Block_codeRepl49_pro_U0_size_out_din);
    size_c_U->if_full_n(size_c_full_n);
    size_c_U->if_write(Block_codeRepl49_pro_U0_size_out_write);
    size_c_U->if_dout(size_c_dout);
    size_c_U->if_empty_n(size_c_empty_n);
    size_c_U->if_read(Loop_sizeLoop_proc_U0_size_read);
    threshold_c_U = new a0_fifo_w32_d2_A("threshold_c_U");
    threshold_c_U->clk(ap_clk);
    threshold_c_U->reset(ap_rst_n_inv);
    threshold_c_U->if_read_ce(ap_var_for_const0);
    threshold_c_U->if_write_ce(ap_var_for_const0);
    threshold_c_U->if_din(Block_codeRepl49_pro_U0_threshold_out_din);
    threshold_c_U->if_full_n(threshold_c_full_n);
    threshold_c_U->if_write(Block_codeRepl49_pro_U0_threshold_out_write);
    threshold_c_U->if_dout(threshold_c_dout);
    threshold_c_U->if_empty_n(threshold_c_empty_n);
    threshold_c_U->if_read(Loop_sizeLoop_proc_U0_threshold_read);
    data0_load_loc_chann_U = new a0_fifo_w32_d2_A("data0_load_loc_chann_U");
    data0_load_loc_chann_U->clk(ap_clk);
    data0_load_loc_chann_U->reset(ap_rst_n_inv);
    data0_load_loc_chann_U->if_read_ce(ap_var_for_const0);
    data0_load_loc_chann_U->if_write_ce(ap_var_for_const0);
    data0_load_loc_chann_U->if_din(Block_codeRepl49_pro_U0_ap_return_0);
    data0_load_loc_chann_U->if_full_n(data0_load_loc_chann_full_n);
    data0_load_loc_chann_U->if_write(ap_channel_done_data0_load_loc_chann);
    data0_load_loc_chann_U->if_dout(data0_load_loc_chann_dout);
    data0_load_loc_chann_U->if_empty_n(data0_load_loc_chann_empty_n);
    data0_load_loc_chann_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_1_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_1_loc_cha_U");
    data0_load_1_loc_cha_U->clk(ap_clk);
    data0_load_1_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_1_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_1_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_1_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_1);
    data0_load_1_loc_cha_U->if_full_n(data0_load_1_loc_cha_full_n);
    data0_load_1_loc_cha_U->if_write(ap_channel_done_data0_load_1_loc_cha);
    data0_load_1_loc_cha_U->if_dout(data0_load_1_loc_cha_dout);
    data0_load_1_loc_cha_U->if_empty_n(data0_load_1_loc_cha_empty_n);
    data0_load_1_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_2_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_2_loc_cha_U");
    data0_load_2_loc_cha_U->clk(ap_clk);
    data0_load_2_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_2_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_2_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_2_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_2);
    data0_load_2_loc_cha_U->if_full_n(data0_load_2_loc_cha_full_n);
    data0_load_2_loc_cha_U->if_write(ap_channel_done_data0_load_2_loc_cha);
    data0_load_2_loc_cha_U->if_dout(data0_load_2_loc_cha_dout);
    data0_load_2_loc_cha_U->if_empty_n(data0_load_2_loc_cha_empty_n);
    data0_load_2_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_3_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_3_loc_cha_U");
    data0_load_3_loc_cha_U->clk(ap_clk);
    data0_load_3_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_3_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_3_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_3_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_3);
    data0_load_3_loc_cha_U->if_full_n(data0_load_3_loc_cha_full_n);
    data0_load_3_loc_cha_U->if_write(ap_channel_done_data0_load_3_loc_cha);
    data0_load_3_loc_cha_U->if_dout(data0_load_3_loc_cha_dout);
    data0_load_3_loc_cha_U->if_empty_n(data0_load_3_loc_cha_empty_n);
    data0_load_3_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_4_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_4_loc_cha_U");
    data0_load_4_loc_cha_U->clk(ap_clk);
    data0_load_4_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_4_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_4_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_4_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_4);
    data0_load_4_loc_cha_U->if_full_n(data0_load_4_loc_cha_full_n);
    data0_load_4_loc_cha_U->if_write(ap_channel_done_data0_load_4_loc_cha);
    data0_load_4_loc_cha_U->if_dout(data0_load_4_loc_cha_dout);
    data0_load_4_loc_cha_U->if_empty_n(data0_load_4_loc_cha_empty_n);
    data0_load_4_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_5_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_5_loc_cha_U");
    data0_load_5_loc_cha_U->clk(ap_clk);
    data0_load_5_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_5_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_5_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_5_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_5);
    data0_load_5_loc_cha_U->if_full_n(data0_load_5_loc_cha_full_n);
    data0_load_5_loc_cha_U->if_write(ap_channel_done_data0_load_5_loc_cha);
    data0_load_5_loc_cha_U->if_dout(data0_load_5_loc_cha_dout);
    data0_load_5_loc_cha_U->if_empty_n(data0_load_5_loc_cha_empty_n);
    data0_load_5_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_6_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_6_loc_cha_U");
    data0_load_6_loc_cha_U->clk(ap_clk);
    data0_load_6_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_6_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_6_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_6_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_6);
    data0_load_6_loc_cha_U->if_full_n(data0_load_6_loc_cha_full_n);
    data0_load_6_loc_cha_U->if_write(ap_channel_done_data0_load_6_loc_cha);
    data0_load_6_loc_cha_U->if_dout(data0_load_6_loc_cha_dout);
    data0_load_6_loc_cha_U->if_empty_n(data0_load_6_loc_cha_empty_n);
    data0_load_6_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_7_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_7_loc_cha_U");
    data0_load_7_loc_cha_U->clk(ap_clk);
    data0_load_7_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_7_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_7_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_7_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_7);
    data0_load_7_loc_cha_U->if_full_n(data0_load_7_loc_cha_full_n);
    data0_load_7_loc_cha_U->if_write(ap_channel_done_data0_load_7_loc_cha);
    data0_load_7_loc_cha_U->if_dout(data0_load_7_loc_cha_dout);
    data0_load_7_loc_cha_U->if_empty_n(data0_load_7_loc_cha_empty_n);
    data0_load_7_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_8_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_8_loc_cha_U");
    data0_load_8_loc_cha_U->clk(ap_clk);
    data0_load_8_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_8_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_8_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_8_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_8);
    data0_load_8_loc_cha_U->if_full_n(data0_load_8_loc_cha_full_n);
    data0_load_8_loc_cha_U->if_write(ap_channel_done_data0_load_8_loc_cha);
    data0_load_8_loc_cha_U->if_dout(data0_load_8_loc_cha_dout);
    data0_load_8_loc_cha_U->if_empty_n(data0_load_8_loc_cha_empty_n);
    data0_load_8_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_9_loc_cha_U = new a0_fifo_w32_d2_A("data0_load_9_loc_cha_U");
    data0_load_9_loc_cha_U->clk(ap_clk);
    data0_load_9_loc_cha_U->reset(ap_rst_n_inv);
    data0_load_9_loc_cha_U->if_read_ce(ap_var_for_const0);
    data0_load_9_loc_cha_U->if_write_ce(ap_var_for_const0);
    data0_load_9_loc_cha_U->if_din(Block_codeRepl49_pro_U0_ap_return_9);
    data0_load_9_loc_cha_U->if_full_n(data0_load_9_loc_cha_full_n);
    data0_load_9_loc_cha_U->if_write(ap_channel_done_data0_load_9_loc_cha);
    data0_load_9_loc_cha_U->if_dout(data0_load_9_loc_cha_dout);
    data0_load_9_loc_cha_U->if_empty_n(data0_load_9_loc_cha_empty_n);
    data0_load_9_loc_cha_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_10_loc_ch_U = new a0_fifo_w32_d2_A("data0_load_10_loc_ch_U");
    data0_load_10_loc_ch_U->clk(ap_clk);
    data0_load_10_loc_ch_U->reset(ap_rst_n_inv);
    data0_load_10_loc_ch_U->if_read_ce(ap_var_for_const0);
    data0_load_10_loc_ch_U->if_write_ce(ap_var_for_const0);
    data0_load_10_loc_ch_U->if_din(Block_codeRepl49_pro_U0_ap_return_10);
    data0_load_10_loc_ch_U->if_full_n(data0_load_10_loc_ch_full_n);
    data0_load_10_loc_ch_U->if_write(ap_channel_done_data0_load_10_loc_ch);
    data0_load_10_loc_ch_U->if_dout(data0_load_10_loc_ch_dout);
    data0_load_10_loc_ch_U->if_empty_n(data0_load_10_loc_ch_empty_n);
    data0_load_10_loc_ch_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_11_loc_ch_U = new a0_fifo_w32_d2_A("data0_load_11_loc_ch_U");
    data0_load_11_loc_ch_U->clk(ap_clk);
    data0_load_11_loc_ch_U->reset(ap_rst_n_inv);
    data0_load_11_loc_ch_U->if_read_ce(ap_var_for_const0);
    data0_load_11_loc_ch_U->if_write_ce(ap_var_for_const0);
    data0_load_11_loc_ch_U->if_din(Block_codeRepl49_pro_U0_ap_return_11);
    data0_load_11_loc_ch_U->if_full_n(data0_load_11_loc_ch_full_n);
    data0_load_11_loc_ch_U->if_write(ap_channel_done_data0_load_11_loc_ch);
    data0_load_11_loc_ch_U->if_dout(data0_load_11_loc_ch_dout);
    data0_load_11_loc_ch_U->if_empty_n(data0_load_11_loc_ch_empty_n);
    data0_load_11_loc_ch_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_12_loc_ch_U = new a0_fifo_w32_d2_A("data0_load_12_loc_ch_U");
    data0_load_12_loc_ch_U->clk(ap_clk);
    data0_load_12_loc_ch_U->reset(ap_rst_n_inv);
    data0_load_12_loc_ch_U->if_read_ce(ap_var_for_const0);
    data0_load_12_loc_ch_U->if_write_ce(ap_var_for_const0);
    data0_load_12_loc_ch_U->if_din(Block_codeRepl49_pro_U0_ap_return_12);
    data0_load_12_loc_ch_U->if_full_n(data0_load_12_loc_ch_full_n);
    data0_load_12_loc_ch_U->if_write(ap_channel_done_data0_load_12_loc_ch);
    data0_load_12_loc_ch_U->if_dout(data0_load_12_loc_ch_dout);
    data0_load_12_loc_ch_U->if_empty_n(data0_load_12_loc_ch_empty_n);
    data0_load_12_loc_ch_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_13_loc_ch_U = new a0_fifo_w32_d2_A("data0_load_13_loc_ch_U");
    data0_load_13_loc_ch_U->clk(ap_clk);
    data0_load_13_loc_ch_U->reset(ap_rst_n_inv);
    data0_load_13_loc_ch_U->if_read_ce(ap_var_for_const0);
    data0_load_13_loc_ch_U->if_write_ce(ap_var_for_const0);
    data0_load_13_loc_ch_U->if_din(Block_codeRepl49_pro_U0_ap_return_13);
    data0_load_13_loc_ch_U->if_full_n(data0_load_13_loc_ch_full_n);
    data0_load_13_loc_ch_U->if_write(ap_channel_done_data0_load_13_loc_ch);
    data0_load_13_loc_ch_U->if_dout(data0_load_13_loc_ch_dout);
    data0_load_13_loc_ch_U->if_empty_n(data0_load_13_loc_ch_empty_n);
    data0_load_13_loc_ch_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_14_loc_ch_U = new a0_fifo_w32_d2_A("data0_load_14_loc_ch_U");
    data0_load_14_loc_ch_U->clk(ap_clk);
    data0_load_14_loc_ch_U->reset(ap_rst_n_inv);
    data0_load_14_loc_ch_U->if_read_ce(ap_var_for_const0);
    data0_load_14_loc_ch_U->if_write_ce(ap_var_for_const0);
    data0_load_14_loc_ch_U->if_din(Block_codeRepl49_pro_U0_ap_return_14);
    data0_load_14_loc_ch_U->if_full_n(data0_load_14_loc_ch_full_n);
    data0_load_14_loc_ch_U->if_write(ap_channel_done_data0_load_14_loc_ch);
    data0_load_14_loc_ch_U->if_dout(data0_load_14_loc_ch_dout);
    data0_load_14_loc_ch_U->if_empty_n(data0_load_14_loc_ch_empty_n);
    data0_load_14_loc_ch_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);
    data0_load_15_loc_ch_U = new a0_fifo_w32_d2_A("data0_load_15_loc_ch_U");
    data0_load_15_loc_ch_U->clk(ap_clk);
    data0_load_15_loc_ch_U->reset(ap_rst_n_inv);
    data0_load_15_loc_ch_U->if_read_ce(ap_var_for_const0);
    data0_load_15_loc_ch_U->if_write_ce(ap_var_for_const0);
    data0_load_15_loc_ch_U->if_din(Block_codeRepl49_pro_U0_ap_return_15);
    data0_load_15_loc_ch_U->if_full_n(data0_load_15_loc_ch_full_n);
    data0_load_15_loc_ch_U->if_write(ap_channel_done_data0_load_15_loc_ch);
    data0_load_15_loc_ch_U->if_dout(data0_load_15_loc_ch_dout);
    data0_load_15_loc_ch_U->if_empty_n(data0_load_15_loc_ch_empty_n);
    data0_load_15_loc_ch_U->if_read(Loop_sizeLoop_proc_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Block_codeRepl49_pro_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_data0_load_15_loc_ch );
    sensitive << ( ap_sync_channel_write_data0_load_14_loc_ch );
    sensitive << ( ap_sync_channel_write_data0_load_13_loc_ch );
    sensitive << ( ap_sync_channel_write_data0_load_12_loc_ch );
    sensitive << ( ap_sync_channel_write_data0_load_11_loc_ch );
    sensitive << ( ap_sync_channel_write_data0_load_10_loc_ch );
    sensitive << ( ap_sync_channel_write_data0_load_9_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_8_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_7_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_6_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_5_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_4_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_3_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_2_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_1_loc_cha );
    sensitive << ( ap_sync_channel_write_data0_load_loc_chann );

    SC_METHOD(thread_Block_codeRepl49_pro_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready );

    SC_METHOD(thread_Block_codeRepl49_pro_U0_start_full_n);

    SC_METHOD(thread_Block_codeRepl49_pro_U0_start_write);

    SC_METHOD(thread_Loop_sizeLoop_proc_U0_ap_continue);

    SC_METHOD(thread_Loop_sizeLoop_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( data0_load_loc_chann_empty_n );
    sensitive << ( data0_load_1_loc_cha_empty_n );
    sensitive << ( data0_load_2_loc_cha_empty_n );
    sensitive << ( data0_load_3_loc_cha_empty_n );
    sensitive << ( data0_load_4_loc_cha_empty_n );
    sensitive << ( data0_load_5_loc_cha_empty_n );
    sensitive << ( data0_load_6_loc_cha_empty_n );
    sensitive << ( data0_load_7_loc_cha_empty_n );
    sensitive << ( data0_load_8_loc_cha_empty_n );
    sensitive << ( data0_load_9_loc_cha_empty_n );
    sensitive << ( data0_load_10_loc_ch_empty_n );
    sensitive << ( data0_load_11_loc_ch_empty_n );
    sensitive << ( data0_load_12_loc_ch_empty_n );
    sensitive << ( data0_load_13_loc_ch_empty_n );
    sensitive << ( data0_load_14_loc_ch_empty_n );
    sensitive << ( data0_load_15_loc_ch_empty_n );
    sensitive << ( ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready );

    SC_METHOD(thread_Loop_sizeLoop_proc_U0_start_full_n);

    SC_METHOD(thread_Loop_sizeLoop_proc_U0_start_write);

    SC_METHOD(thread_ap_channel_done_data0_load_10_loc_ch);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_10_loc_ch );

    SC_METHOD(thread_ap_channel_done_data0_load_11_loc_ch);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_11_loc_ch );

    SC_METHOD(thread_ap_channel_done_data0_load_12_loc_ch);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_12_loc_ch );

    SC_METHOD(thread_ap_channel_done_data0_load_13_loc_ch);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_13_loc_ch );

    SC_METHOD(thread_ap_channel_done_data0_load_14_loc_ch);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_14_loc_ch );

    SC_METHOD(thread_ap_channel_done_data0_load_15_loc_ch);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_15_loc_ch );

    SC_METHOD(thread_ap_channel_done_data0_load_1_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_1_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_2_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_2_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_3_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_3_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_4_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_4_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_5_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_5_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_6_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_6_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_7_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_7_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_8_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_8_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_9_loc_cha);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_9_loc_cha );

    SC_METHOD(thread_ap_channel_done_data0_load_loc_chann);
    sensitive << ( Block_codeRepl49_pro_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_data0_load_loc_chann );

    SC_METHOD(thread_ap_done);
    sensitive << ( Loop_sizeLoop_proc_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_codeRepl49_pro_U0_ap_idle );
    sensitive << ( Loop_sizeLoop_proc_U0_ap_idle );
    sensitive << ( data0_load_loc_chann_empty_n );
    sensitive << ( data0_load_1_loc_cha_empty_n );
    sensitive << ( data0_load_2_loc_cha_empty_n );
    sensitive << ( data0_load_3_loc_cha_empty_n );
    sensitive << ( data0_load_4_loc_cha_empty_n );
    sensitive << ( data0_load_5_loc_cha_empty_n );
    sensitive << ( data0_load_6_loc_cha_empty_n );
    sensitive << ( data0_load_7_loc_cha_empty_n );
    sensitive << ( data0_load_8_loc_cha_empty_n );
    sensitive << ( data0_load_9_loc_cha_empty_n );
    sensitive << ( data0_load_10_loc_ch_empty_n );
    sensitive << ( data0_load_11_loc_ch_empty_n );
    sensitive << ( data0_load_12_loc_ch_empty_n );
    sensitive << ( data0_load_13_loc_ch_empty_n );
    sensitive << ( data0_load_14_loc_ch_empty_n );
    sensitive << ( data0_load_15_loc_ch_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_Block_codeRepl49_pro_U0_ap_ready);
    sensitive << ( Block_codeRepl49_pro_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Loop_sizeLoop_proc_U0_ap_ready);
    sensitive << ( Loop_sizeLoop_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_10_loc_ch);
    sensitive << ( ap_channel_done_data0_load_10_loc_ch );
    sensitive << ( data0_load_10_loc_ch_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_10_loc_ch );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_11_loc_ch);
    sensitive << ( ap_channel_done_data0_load_11_loc_ch );
    sensitive << ( data0_load_11_loc_ch_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_11_loc_ch );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_12_loc_ch);
    sensitive << ( ap_channel_done_data0_load_12_loc_ch );
    sensitive << ( data0_load_12_loc_ch_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_12_loc_ch );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_13_loc_ch);
    sensitive << ( ap_channel_done_data0_load_13_loc_ch );
    sensitive << ( data0_load_13_loc_ch_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_13_loc_ch );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_14_loc_ch);
    sensitive << ( ap_channel_done_data0_load_14_loc_ch );
    sensitive << ( data0_load_14_loc_ch_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_14_loc_ch );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_15_loc_ch);
    sensitive << ( ap_channel_done_data0_load_15_loc_ch );
    sensitive << ( data0_load_15_loc_ch_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_15_loc_ch );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_1_loc_cha);
    sensitive << ( ap_channel_done_data0_load_1_loc_cha );
    sensitive << ( data0_load_1_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_1_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_2_loc_cha);
    sensitive << ( ap_channel_done_data0_load_2_loc_cha );
    sensitive << ( data0_load_2_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_2_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_3_loc_cha);
    sensitive << ( ap_channel_done_data0_load_3_loc_cha );
    sensitive << ( data0_load_3_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_3_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_4_loc_cha);
    sensitive << ( ap_channel_done_data0_load_4_loc_cha );
    sensitive << ( data0_load_4_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_4_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_5_loc_cha);
    sensitive << ( ap_channel_done_data0_load_5_loc_cha );
    sensitive << ( data0_load_5_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_5_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_6_loc_cha);
    sensitive << ( ap_channel_done_data0_load_6_loc_cha );
    sensitive << ( data0_load_6_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_6_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_7_loc_cha);
    sensitive << ( ap_channel_done_data0_load_7_loc_cha );
    sensitive << ( data0_load_7_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_7_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_8_loc_cha);
    sensitive << ( ap_channel_done_data0_load_8_loc_cha );
    sensitive << ( data0_load_8_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_8_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_9_loc_cha);
    sensitive << ( ap_channel_done_data0_load_9_loc_cha );
    sensitive << ( data0_load_9_loc_cha_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_9_loc_cha );

    SC_METHOD(thread_ap_sync_channel_write_data0_load_loc_chann);
    sensitive << ( ap_channel_done_data0_load_loc_chann );
    sensitive << ( data0_load_loc_chann_full_n );
    sensitive << ( ap_sync_reg_channel_write_data0_load_loc_chann );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Loop_sizeLoop_proc_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Block_codeRepl49_pro_U0_ap_ready );
    sensitive << ( ap_sync_Loop_sizeLoop_proc_U0_ap_ready );

    SC_METHOD(thread_data0_read);
    sensitive << ( Block_codeRepl49_pro_U0_data0_read );

    SC_METHOD(thread_data1_read);
    sensitive << ( Loop_sizeLoop_proc_U0_data1_read );

    SC_METHOD(thread_data2_din);
    sensitive << ( Loop_sizeLoop_proc_U0_data2_din );

    SC_METHOD(thread_data2_write);
    sensitive << ( Loop_sizeLoop_proc_U0_data2_write );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_channel_write_data0_load_15_loc_ch = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_14_loc_ch = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_13_loc_ch = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_12_loc_ch = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_11_loc_ch = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_10_loc_ch = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_9_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_8_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_7_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_6_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_5_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_4_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_3_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_2_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_1_loc_cha = SC_LOGIC_0;
    ap_sync_reg_channel_write_data0_load_loc_chann = SC_LOGIC_0;
    ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready = SC_LOGIC_0;
    Block_codeRepl49_pro_U0_ap_ready_count = "00";
    ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready = SC_LOGIC_0;
    Loop_sizeLoop_proc_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "a0_myFuncAccel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, size, "(port)size");
    sc_trace(mVcdFile, dim, "(port)dim");
    sc_trace(mVcdFile, threshold, "(port)threshold");
    sc_trace(mVcdFile, data0_dout, "(port)data0_dout");
    sc_trace(mVcdFile, data0_empty_n, "(port)data0_empty_n");
    sc_trace(mVcdFile, data0_read, "(port)data0_read");
    sc_trace(mVcdFile, data1_dout, "(port)data1_dout");
    sc_trace(mVcdFile, data1_empty_n, "(port)data1_empty_n");
    sc_trace(mVcdFile, data1_read, "(port)data1_read");
    sc_trace(mVcdFile, data2_din, "(port)data2_din");
    sc_trace(mVcdFile, data2_full_n, "(port)data2_full_n");
    sc_trace(mVcdFile, data2_write, "(port)data2_write");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_start, "Block_codeRepl49_pro_U0_ap_start");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_done, "Block_codeRepl49_pro_U0_ap_done");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_continue, "Block_codeRepl49_pro_U0_ap_continue");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_idle, "Block_codeRepl49_pro_U0_ap_idle");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_ready, "Block_codeRepl49_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_data0_read, "Block_codeRepl49_pro_U0_data0_read");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_size_out_din, "Block_codeRepl49_pro_U0_size_out_din");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_size_out_write, "Block_codeRepl49_pro_U0_size_out_write");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_threshold_out_din, "Block_codeRepl49_pro_U0_threshold_out_din");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_threshold_out_write, "Block_codeRepl49_pro_U0_threshold_out_write");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_0, "Block_codeRepl49_pro_U0_ap_return_0");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_1, "Block_codeRepl49_pro_U0_ap_return_1");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_2, "Block_codeRepl49_pro_U0_ap_return_2");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_3, "Block_codeRepl49_pro_U0_ap_return_3");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_4, "Block_codeRepl49_pro_U0_ap_return_4");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_5, "Block_codeRepl49_pro_U0_ap_return_5");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_6, "Block_codeRepl49_pro_U0_ap_return_6");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_7, "Block_codeRepl49_pro_U0_ap_return_7");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_8, "Block_codeRepl49_pro_U0_ap_return_8");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_9, "Block_codeRepl49_pro_U0_ap_return_9");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_10, "Block_codeRepl49_pro_U0_ap_return_10");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_11, "Block_codeRepl49_pro_U0_ap_return_11");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_12, "Block_codeRepl49_pro_U0_ap_return_12");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_13, "Block_codeRepl49_pro_U0_ap_return_13");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_14, "Block_codeRepl49_pro_U0_ap_return_14");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_return_15, "Block_codeRepl49_pro_U0_ap_return_15");
    sc_trace(mVcdFile, ap_channel_done_data0_load_15_loc_ch, "ap_channel_done_data0_load_15_loc_ch");
    sc_trace(mVcdFile, data0_load_15_loc_ch_full_n, "data0_load_15_loc_ch_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_15_loc_ch, "ap_sync_reg_channel_write_data0_load_15_loc_ch");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_15_loc_ch, "ap_sync_channel_write_data0_load_15_loc_ch");
    sc_trace(mVcdFile, ap_channel_done_data0_load_14_loc_ch, "ap_channel_done_data0_load_14_loc_ch");
    sc_trace(mVcdFile, data0_load_14_loc_ch_full_n, "data0_load_14_loc_ch_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_14_loc_ch, "ap_sync_reg_channel_write_data0_load_14_loc_ch");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_14_loc_ch, "ap_sync_channel_write_data0_load_14_loc_ch");
    sc_trace(mVcdFile, ap_channel_done_data0_load_13_loc_ch, "ap_channel_done_data0_load_13_loc_ch");
    sc_trace(mVcdFile, data0_load_13_loc_ch_full_n, "data0_load_13_loc_ch_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_13_loc_ch, "ap_sync_reg_channel_write_data0_load_13_loc_ch");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_13_loc_ch, "ap_sync_channel_write_data0_load_13_loc_ch");
    sc_trace(mVcdFile, ap_channel_done_data0_load_12_loc_ch, "ap_channel_done_data0_load_12_loc_ch");
    sc_trace(mVcdFile, data0_load_12_loc_ch_full_n, "data0_load_12_loc_ch_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_12_loc_ch, "ap_sync_reg_channel_write_data0_load_12_loc_ch");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_12_loc_ch, "ap_sync_channel_write_data0_load_12_loc_ch");
    sc_trace(mVcdFile, ap_channel_done_data0_load_11_loc_ch, "ap_channel_done_data0_load_11_loc_ch");
    sc_trace(mVcdFile, data0_load_11_loc_ch_full_n, "data0_load_11_loc_ch_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_11_loc_ch, "ap_sync_reg_channel_write_data0_load_11_loc_ch");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_11_loc_ch, "ap_sync_channel_write_data0_load_11_loc_ch");
    sc_trace(mVcdFile, ap_channel_done_data0_load_10_loc_ch, "ap_channel_done_data0_load_10_loc_ch");
    sc_trace(mVcdFile, data0_load_10_loc_ch_full_n, "data0_load_10_loc_ch_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_10_loc_ch, "ap_sync_reg_channel_write_data0_load_10_loc_ch");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_10_loc_ch, "ap_sync_channel_write_data0_load_10_loc_ch");
    sc_trace(mVcdFile, ap_channel_done_data0_load_9_loc_cha, "ap_channel_done_data0_load_9_loc_cha");
    sc_trace(mVcdFile, data0_load_9_loc_cha_full_n, "data0_load_9_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_9_loc_cha, "ap_sync_reg_channel_write_data0_load_9_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_9_loc_cha, "ap_sync_channel_write_data0_load_9_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_8_loc_cha, "ap_channel_done_data0_load_8_loc_cha");
    sc_trace(mVcdFile, data0_load_8_loc_cha_full_n, "data0_load_8_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_8_loc_cha, "ap_sync_reg_channel_write_data0_load_8_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_8_loc_cha, "ap_sync_channel_write_data0_load_8_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_7_loc_cha, "ap_channel_done_data0_load_7_loc_cha");
    sc_trace(mVcdFile, data0_load_7_loc_cha_full_n, "data0_load_7_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_7_loc_cha, "ap_sync_reg_channel_write_data0_load_7_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_7_loc_cha, "ap_sync_channel_write_data0_load_7_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_6_loc_cha, "ap_channel_done_data0_load_6_loc_cha");
    sc_trace(mVcdFile, data0_load_6_loc_cha_full_n, "data0_load_6_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_6_loc_cha, "ap_sync_reg_channel_write_data0_load_6_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_6_loc_cha, "ap_sync_channel_write_data0_load_6_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_5_loc_cha, "ap_channel_done_data0_load_5_loc_cha");
    sc_trace(mVcdFile, data0_load_5_loc_cha_full_n, "data0_load_5_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_5_loc_cha, "ap_sync_reg_channel_write_data0_load_5_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_5_loc_cha, "ap_sync_channel_write_data0_load_5_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_4_loc_cha, "ap_channel_done_data0_load_4_loc_cha");
    sc_trace(mVcdFile, data0_load_4_loc_cha_full_n, "data0_load_4_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_4_loc_cha, "ap_sync_reg_channel_write_data0_load_4_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_4_loc_cha, "ap_sync_channel_write_data0_load_4_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_3_loc_cha, "ap_channel_done_data0_load_3_loc_cha");
    sc_trace(mVcdFile, data0_load_3_loc_cha_full_n, "data0_load_3_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_3_loc_cha, "ap_sync_reg_channel_write_data0_load_3_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_3_loc_cha, "ap_sync_channel_write_data0_load_3_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_2_loc_cha, "ap_channel_done_data0_load_2_loc_cha");
    sc_trace(mVcdFile, data0_load_2_loc_cha_full_n, "data0_load_2_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_2_loc_cha, "ap_sync_reg_channel_write_data0_load_2_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_2_loc_cha, "ap_sync_channel_write_data0_load_2_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_1_loc_cha, "ap_channel_done_data0_load_1_loc_cha");
    sc_trace(mVcdFile, data0_load_1_loc_cha_full_n, "data0_load_1_loc_cha_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_1_loc_cha, "ap_sync_reg_channel_write_data0_load_1_loc_cha");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_1_loc_cha, "ap_sync_channel_write_data0_load_1_loc_cha");
    sc_trace(mVcdFile, ap_channel_done_data0_load_loc_chann, "ap_channel_done_data0_load_loc_chann");
    sc_trace(mVcdFile, data0_load_loc_chann_full_n, "data0_load_loc_chann_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_data0_load_loc_chann, "ap_sync_reg_channel_write_data0_load_loc_chann");
    sc_trace(mVcdFile, ap_sync_channel_write_data0_load_loc_chann, "ap_sync_channel_write_data0_load_loc_chann");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_ap_start, "Loop_sizeLoop_proc_U0_ap_start");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_ap_done, "Loop_sizeLoop_proc_U0_ap_done");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_ap_continue, "Loop_sizeLoop_proc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_ap_idle, "Loop_sizeLoop_proc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_ap_ready, "Loop_sizeLoop_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_size_read, "Loop_sizeLoop_proc_U0_size_read");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_data1_read, "Loop_sizeLoop_proc_U0_data1_read");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_threshold_read, "Loop_sizeLoop_proc_U0_threshold_read");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_data2_din, "Loop_sizeLoop_proc_U0_data2_din");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_data2_write, "Loop_sizeLoop_proc_U0_data2_write");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, size_c_full_n, "size_c_full_n");
    sc_trace(mVcdFile, size_c_dout, "size_c_dout");
    sc_trace(mVcdFile, size_c_empty_n, "size_c_empty_n");
    sc_trace(mVcdFile, threshold_c_full_n, "threshold_c_full_n");
    sc_trace(mVcdFile, threshold_c_dout, "threshold_c_dout");
    sc_trace(mVcdFile, threshold_c_empty_n, "threshold_c_empty_n");
    sc_trace(mVcdFile, data0_load_loc_chann_dout, "data0_load_loc_chann_dout");
    sc_trace(mVcdFile, data0_load_loc_chann_empty_n, "data0_load_loc_chann_empty_n");
    sc_trace(mVcdFile, data0_load_1_loc_cha_dout, "data0_load_1_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_1_loc_cha_empty_n, "data0_load_1_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_2_loc_cha_dout, "data0_load_2_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_2_loc_cha_empty_n, "data0_load_2_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_3_loc_cha_dout, "data0_load_3_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_3_loc_cha_empty_n, "data0_load_3_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_4_loc_cha_dout, "data0_load_4_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_4_loc_cha_empty_n, "data0_load_4_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_5_loc_cha_dout, "data0_load_5_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_5_loc_cha_empty_n, "data0_load_5_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_6_loc_cha_dout, "data0_load_6_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_6_loc_cha_empty_n, "data0_load_6_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_7_loc_cha_dout, "data0_load_7_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_7_loc_cha_empty_n, "data0_load_7_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_8_loc_cha_dout, "data0_load_8_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_8_loc_cha_empty_n, "data0_load_8_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_9_loc_cha_dout, "data0_load_9_loc_cha_dout");
    sc_trace(mVcdFile, data0_load_9_loc_cha_empty_n, "data0_load_9_loc_cha_empty_n");
    sc_trace(mVcdFile, data0_load_10_loc_ch_dout, "data0_load_10_loc_ch_dout");
    sc_trace(mVcdFile, data0_load_10_loc_ch_empty_n, "data0_load_10_loc_ch_empty_n");
    sc_trace(mVcdFile, data0_load_11_loc_ch_dout, "data0_load_11_loc_ch_dout");
    sc_trace(mVcdFile, data0_load_11_loc_ch_empty_n, "data0_load_11_loc_ch_empty_n");
    sc_trace(mVcdFile, data0_load_12_loc_ch_dout, "data0_load_12_loc_ch_dout");
    sc_trace(mVcdFile, data0_load_12_loc_ch_empty_n, "data0_load_12_loc_ch_empty_n");
    sc_trace(mVcdFile, data0_load_13_loc_ch_dout, "data0_load_13_loc_ch_dout");
    sc_trace(mVcdFile, data0_load_13_loc_ch_empty_n, "data0_load_13_loc_ch_empty_n");
    sc_trace(mVcdFile, data0_load_14_loc_ch_dout, "data0_load_14_loc_ch_dout");
    sc_trace(mVcdFile, data0_load_14_loc_ch_empty_n, "data0_load_14_loc_ch_empty_n");
    sc_trace(mVcdFile, data0_load_15_loc_ch_dout, "data0_load_15_loc_ch_dout");
    sc_trace(mVcdFile, data0_load_15_loc_ch_empty_n, "data0_load_15_loc_ch_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready, "ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_codeRepl49_pro_U0_ap_ready, "ap_sync_Block_codeRepl49_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_ap_ready_count, "Block_codeRepl49_pro_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready, "ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Loop_sizeLoop_proc_U0_ap_ready, "ap_sync_Loop_sizeLoop_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_ap_ready_count, "Loop_sizeLoop_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_start_full_n, "Block_codeRepl49_pro_U0_start_full_n");
    sc_trace(mVcdFile, Block_codeRepl49_pro_U0_start_write, "Block_codeRepl49_pro_U0_start_write");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_start_full_n, "Loop_sizeLoop_proc_U0_start_full_n");
    sc_trace(mVcdFile, Loop_sizeLoop_proc_U0_start_write, "Loop_sizeLoop_proc_U0_start_write");
#endif

    }
    mHdltvinHandle.open("a0_myFuncAccel.hdltvin.dat");
    mHdltvoutHandle.open("a0_myFuncAccel.hdltvout.dat");
}

a0_myFuncAccel::~a0_myFuncAccel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Block_codeRepl49_pro_U0;
    delete Loop_sizeLoop_proc_U0;
    delete size_c_U;
    delete threshold_c_U;
    delete data0_load_loc_chann_U;
    delete data0_load_1_loc_cha_U;
    delete data0_load_2_loc_cha_U;
    delete data0_load_3_loc_cha_U;
    delete data0_load_4_loc_cha_U;
    delete data0_load_5_loc_cha_U;
    delete data0_load_6_loc_cha_U;
    delete data0_load_7_loc_cha_U;
    delete data0_load_8_loc_cha_U;
    delete data0_load_9_loc_cha_U;
    delete data0_load_10_loc_ch_U;
    delete data0_load_11_loc_ch_U;
    delete data0_load_12_loc_ch_U;
    delete data0_load_13_loc_ch_U;
    delete data0_load_14_loc_ch_U;
    delete data0_load_15_loc_ch_U;
}

void a0_myFuncAccel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void a0_myFuncAccel::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, Block_codeRepl49_pro_U0_ap_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Block_codeRepl49_pro_U0_ap_ready_count = (!Block_codeRepl49_pro_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_codeRepl49_pro_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(Block_codeRepl49_pro_U0_ap_ready.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()))) {
        Block_codeRepl49_pro_U0_ap_ready_count = (!Block_codeRepl49_pro_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_codeRepl49_pro_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, Loop_sizeLoop_proc_U0_ap_ready.read()))) {
        Loop_sizeLoop_proc_U0_ap_ready_count = (!Loop_sizeLoop_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_sizeLoop_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, Loop_sizeLoop_proc_U0_ap_ready.read()))) {
        Loop_sizeLoop_proc_U0_ap_ready_count = (!Loop_sizeLoop_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Loop_sizeLoop_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready = ap_sync_Block_codeRepl49_pro_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready = ap_sync_Loop_sizeLoop_proc_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_10_loc_ch = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_10_loc_ch = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_10_loc_ch = ap_sync_channel_write_data0_load_10_loc_ch.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_11_loc_ch = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_11_loc_ch = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_11_loc_ch = ap_sync_channel_write_data0_load_11_loc_ch.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_12_loc_ch = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_12_loc_ch = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_12_loc_ch = ap_sync_channel_write_data0_load_12_loc_ch.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_13_loc_ch = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_13_loc_ch = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_13_loc_ch = ap_sync_channel_write_data0_load_13_loc_ch.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_14_loc_ch = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_14_loc_ch = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_14_loc_ch = ap_sync_channel_write_data0_load_14_loc_ch.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_15_loc_ch = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_15_loc_ch = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_15_loc_ch = ap_sync_channel_write_data0_load_15_loc_ch.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_1_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_1_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_1_loc_cha = ap_sync_channel_write_data0_load_1_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_2_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_2_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_2_loc_cha = ap_sync_channel_write_data0_load_2_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_3_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_3_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_3_loc_cha = ap_sync_channel_write_data0_load_3_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_4_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_4_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_4_loc_cha = ap_sync_channel_write_data0_load_4_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_5_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_5_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_5_loc_cha = ap_sync_channel_write_data0_load_5_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_6_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_6_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_6_loc_cha = ap_sync_channel_write_data0_load_6_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_7_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_7_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_7_loc_cha = ap_sync_channel_write_data0_load_7_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_8_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_8_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_8_loc_cha = ap_sync_channel_write_data0_load_8_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_9_loc_cha = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_9_loc_cha = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_9_loc_cha = ap_sync_channel_write_data0_load_9_loc_cha.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_data0_load_loc_chann = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_codeRepl49_pro_U0_ap_done.read() & 
             Block_codeRepl49_pro_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_data0_load_loc_chann = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_data0_load_loc_chann = ap_sync_channel_write_data0_load_loc_chann.read();
        }
    }
}

void a0_myFuncAccel::thread_Block_codeRepl49_pro_U0_ap_continue() {
    Block_codeRepl49_pro_U0_ap_continue = (ap_sync_channel_write_data0_load_15_loc_ch.read() & ap_sync_channel_write_data0_load_14_loc_ch.read() & ap_sync_channel_write_data0_load_13_loc_ch.read() & ap_sync_channel_write_data0_load_12_loc_ch.read() & ap_sync_channel_write_data0_load_11_loc_ch.read() & ap_sync_channel_write_data0_load_10_loc_ch.read() & ap_sync_channel_write_data0_load_9_loc_cha.read() & ap_sync_channel_write_data0_load_8_loc_cha.read() & ap_sync_channel_write_data0_load_7_loc_cha.read() & ap_sync_channel_write_data0_load_6_loc_cha.read() & ap_sync_channel_write_data0_load_5_loc_cha.read() & ap_sync_channel_write_data0_load_4_loc_cha.read() & ap_sync_channel_write_data0_load_3_loc_cha.read() & ap_sync_channel_write_data0_load_2_loc_cha.read() & ap_sync_channel_write_data0_load_1_loc_cha.read() & ap_sync_channel_write_data0_load_loc_chann.read());
}

void a0_myFuncAccel::thread_Block_codeRepl49_pro_U0_ap_start() {
    Block_codeRepl49_pro_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_Block_codeRepl49_pro_U0_start_full_n() {
    Block_codeRepl49_pro_U0_start_full_n = ap_const_logic_1;
}

void a0_myFuncAccel::thread_Block_codeRepl49_pro_U0_start_write() {
    Block_codeRepl49_pro_U0_start_write = ap_const_logic_0;
}

void a0_myFuncAccel::thread_Loop_sizeLoop_proc_U0_ap_continue() {
    Loop_sizeLoop_proc_U0_ap_continue = ap_const_logic_1;
}

void a0_myFuncAccel::thread_Loop_sizeLoop_proc_U0_ap_start() {
    Loop_sizeLoop_proc_U0_ap_start = (ap_start.read() & data0_load_loc_chann_empty_n.read() & data0_load_1_loc_cha_empty_n.read() & data0_load_2_loc_cha_empty_n.read() & data0_load_3_loc_cha_empty_n.read() & data0_load_4_loc_cha_empty_n.read() & data0_load_5_loc_cha_empty_n.read() & data0_load_6_loc_cha_empty_n.read() & data0_load_7_loc_cha_empty_n.read() & data0_load_8_loc_cha_empty_n.read() & data0_load_9_loc_cha_empty_n.read() & data0_load_10_loc_ch_empty_n.read() & data0_load_11_loc_ch_empty_n.read() & data0_load_12_loc_ch_empty_n.read() & data0_load_13_loc_ch_empty_n.read() & data0_load_14_loc_ch_empty_n.read() & data0_load_15_loc_ch_empty_n.read() & (ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_Loop_sizeLoop_proc_U0_start_full_n() {
    Loop_sizeLoop_proc_U0_start_full_n = ap_const_logic_1;
}

void a0_myFuncAccel::thread_Loop_sizeLoop_proc_U0_start_write() {
    Loop_sizeLoop_proc_U0_start_write = ap_const_logic_0;
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_10_loc_ch() {
    ap_channel_done_data0_load_10_loc_ch = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_10_loc_ch.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_11_loc_ch() {
    ap_channel_done_data0_load_11_loc_ch = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_11_loc_ch.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_12_loc_ch() {
    ap_channel_done_data0_load_12_loc_ch = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_12_loc_ch.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_13_loc_ch() {
    ap_channel_done_data0_load_13_loc_ch = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_13_loc_ch.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_14_loc_ch() {
    ap_channel_done_data0_load_14_loc_ch = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_14_loc_ch.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_15_loc_ch() {
    ap_channel_done_data0_load_15_loc_ch = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_15_loc_ch.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_1_loc_cha() {
    ap_channel_done_data0_load_1_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_1_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_2_loc_cha() {
    ap_channel_done_data0_load_2_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_2_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_3_loc_cha() {
    ap_channel_done_data0_load_3_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_3_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_4_loc_cha() {
    ap_channel_done_data0_load_4_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_4_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_5_loc_cha() {
    ap_channel_done_data0_load_5_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_5_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_6_loc_cha() {
    ap_channel_done_data0_load_6_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_6_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_7_loc_cha() {
    ap_channel_done_data0_load_7_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_7_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_8_loc_cha() {
    ap_channel_done_data0_load_8_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_8_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_9_loc_cha() {
    ap_channel_done_data0_load_9_loc_cha = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_9_loc_cha.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_channel_done_data0_load_loc_chann() {
    ap_channel_done_data0_load_loc_chann = (Block_codeRepl49_pro_U0_ap_done.read() & (ap_sync_reg_channel_write_data0_load_loc_chann.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_done() {
    ap_done = Loop_sizeLoop_proc_U0_ap_done.read();
}

void a0_myFuncAccel::thread_ap_idle() {
    ap_idle = (Block_codeRepl49_pro_U0_ap_idle.read() & Loop_sizeLoop_proc_U0_ap_idle.read() & (data0_load_loc_chann_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_1_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_2_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_3_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_4_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_5_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_6_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_7_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_8_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_9_loc_cha_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_10_loc_ch_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_11_loc_ch_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_12_loc_ch_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_13_loc_ch_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_14_loc_ch_empty_n.read() ^ 
  ap_const_logic_1) & (data0_load_15_loc_ch_empty_n.read() ^ 
  ap_const_logic_1));
}

void a0_myFuncAccel::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void a0_myFuncAccel::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void a0_myFuncAccel::thread_ap_sync_Block_codeRepl49_pro_U0_ap_ready() {
    ap_sync_Block_codeRepl49_pro_U0_ap_ready = (Block_codeRepl49_pro_U0_ap_ready.read() | ap_sync_reg_Block_codeRepl49_pro_U0_ap_ready.read());
}

void a0_myFuncAccel::thread_ap_sync_Loop_sizeLoop_proc_U0_ap_ready() {
    ap_sync_Loop_sizeLoop_proc_U0_ap_ready = (Loop_sizeLoop_proc_U0_ap_ready.read() | ap_sync_reg_Loop_sizeLoop_proc_U0_ap_ready.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_10_loc_ch() {
    ap_sync_channel_write_data0_load_10_loc_ch = ((ap_channel_done_data0_load_10_loc_ch.read() & 
  data0_load_10_loc_ch_full_n.read()) | ap_sync_reg_channel_write_data0_load_10_loc_ch.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_11_loc_ch() {
    ap_sync_channel_write_data0_load_11_loc_ch = ((ap_channel_done_data0_load_11_loc_ch.read() & 
  data0_load_11_loc_ch_full_n.read()) | ap_sync_reg_channel_write_data0_load_11_loc_ch.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_12_loc_ch() {
    ap_sync_channel_write_data0_load_12_loc_ch = ((ap_channel_done_data0_load_12_loc_ch.read() & 
  data0_load_12_loc_ch_full_n.read()) | ap_sync_reg_channel_write_data0_load_12_loc_ch.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_13_loc_ch() {
    ap_sync_channel_write_data0_load_13_loc_ch = ((ap_channel_done_data0_load_13_loc_ch.read() & 
  data0_load_13_loc_ch_full_n.read()) | ap_sync_reg_channel_write_data0_load_13_loc_ch.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_14_loc_ch() {
    ap_sync_channel_write_data0_load_14_loc_ch = ((ap_channel_done_data0_load_14_loc_ch.read() & 
  data0_load_14_loc_ch_full_n.read()) | ap_sync_reg_channel_write_data0_load_14_loc_ch.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_15_loc_ch() {
    ap_sync_channel_write_data0_load_15_loc_ch = ((ap_channel_done_data0_load_15_loc_ch.read() & 
  data0_load_15_loc_ch_full_n.read()) | ap_sync_reg_channel_write_data0_load_15_loc_ch.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_1_loc_cha() {
    ap_sync_channel_write_data0_load_1_loc_cha = ((ap_channel_done_data0_load_1_loc_cha.read() & 
  data0_load_1_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_1_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_2_loc_cha() {
    ap_sync_channel_write_data0_load_2_loc_cha = ((ap_channel_done_data0_load_2_loc_cha.read() & 
  data0_load_2_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_2_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_3_loc_cha() {
    ap_sync_channel_write_data0_load_3_loc_cha = ((ap_channel_done_data0_load_3_loc_cha.read() & 
  data0_load_3_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_3_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_4_loc_cha() {
    ap_sync_channel_write_data0_load_4_loc_cha = ((ap_channel_done_data0_load_4_loc_cha.read() & 
  data0_load_4_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_4_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_5_loc_cha() {
    ap_sync_channel_write_data0_load_5_loc_cha = ((ap_channel_done_data0_load_5_loc_cha.read() & 
  data0_load_5_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_5_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_6_loc_cha() {
    ap_sync_channel_write_data0_load_6_loc_cha = ((ap_channel_done_data0_load_6_loc_cha.read() & 
  data0_load_6_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_6_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_7_loc_cha() {
    ap_sync_channel_write_data0_load_7_loc_cha = ((ap_channel_done_data0_load_7_loc_cha.read() & 
  data0_load_7_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_7_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_8_loc_cha() {
    ap_sync_channel_write_data0_load_8_loc_cha = ((ap_channel_done_data0_load_8_loc_cha.read() & 
  data0_load_8_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_8_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_9_loc_cha() {
    ap_sync_channel_write_data0_load_9_loc_cha = ((ap_channel_done_data0_load_9_loc_cha.read() & 
  data0_load_9_loc_cha_full_n.read()) | ap_sync_reg_channel_write_data0_load_9_loc_cha.read());
}

void a0_myFuncAccel::thread_ap_sync_channel_write_data0_load_loc_chann() {
    ap_sync_channel_write_data0_load_loc_chann = ((ap_channel_done_data0_load_loc_chann.read() & 
  data0_load_loc_chann_full_n.read()) | ap_sync_reg_channel_write_data0_load_loc_chann.read());
}

void a0_myFuncAccel::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void a0_myFuncAccel::thread_ap_sync_done() {
    ap_sync_done = Loop_sizeLoop_proc_U0_ap_done.read();
}

void a0_myFuncAccel::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Block_codeRepl49_pro_U0_ap_ready.read() & ap_sync_Loop_sizeLoop_proc_U0_ap_ready.read());
}

void a0_myFuncAccel::thread_data0_read() {
    data0_read = Block_codeRepl49_pro_U0_data0_read.read();
}

void a0_myFuncAccel::thread_data1_read() {
    data1_read = Loop_sizeLoop_proc_U0_data1_read.read();
}

void a0_myFuncAccel::thread_data2_din() {
    data2_din = Loop_sizeLoop_proc_U0_data2_din.read();
}

void a0_myFuncAccel::thread_data2_write() {
    data2_write = Loop_sizeLoop_proc_U0_data2_write.read();
}

void a0_myFuncAccel::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"size\" :  \"" << size.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dim\" :  \"" << dim.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"threshold\" :  \"" << threshold.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data0_dout\" :  \"" << data0_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data0_empty_n\" :  \"" << data0_empty_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"data0_read\" :  \"" << data0_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data1_dout\" :  \"" << data1_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data1_empty_n\" :  \"" << data1_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"data1_read\" :  \"" << data1_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"data2_din\" :  \"" << data2_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data2_full_n\" :  \"" << data2_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"data2_write\" :  \"" << data2_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

