# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_myFuncAccel_1_0/zed_myFuncAccel_1_0.xci
# IP: The module: 'zed_myFuncAccel_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_myFuncAccel_1_0/constraints/a0_myFuncAccel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_myFuncAccel_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_myFuncAccel_1_0/zed_myFuncAccel_1_0.xci
# IP: The module: 'zed_myFuncAccel_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/skalogerakis/TUC_Projects/TUC_HLS/MyCode/MIlestone3/SDSOC_Accel/Algo_4/Debug/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_myFuncAccel_1_0/constraints/a0_myFuncAccel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_myFuncAccel_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
