# This file was automatically generated by SDx
# To open the vivado project generated by the Sdx, run the following command
# vivado -source openprj.tcl

namespace eval ::sdx {
  set mode impl
}; # end of namespace ::sdx

puts "--- DEBUG: source scripts/_vivado_params.tcl"
source scripts/_vivado_params.tcl
open_project prj/prj.xpr
