// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myFuncAccel,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=4054,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=23,HLS_SYN_FF=4502,HLS_SYN_LUT=4800,HLS_VERSION=2018_3}" *)

module myFuncAccel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        size,
        dim,
        threshold,
        data0_req_din,
        data0_req_full_n,
        data0_req_write,
        data0_rsp_empty_n,
        data0_rsp_read,
        data0_address,
        data0_datain,
        data0_dataout,
        data0_size,
        data1_req_din,
        data1_req_full_n,
        data1_req_write,
        data1_rsp_empty_n,
        data1_rsp_read,
        data1_address,
        data1_datain,
        data1_dataout,
        data1_size,
        data2_req_din,
        data2_req_full_n,
        data2_req_write,
        data2_rsp_empty_n,
        data2_rsp_read,
        data2_address,
        data2_datain,
        data2_dataout,
        data2_size
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_pp0_stage0 = 23'd262144;
parameter    ap_ST_fsm_pp0_stage1 = 23'd524288;
parameter    ap_ST_fsm_pp0_stage2 = 23'd1048576;
parameter    ap_ST_fsm_pp0_stage3 = 23'd2097152;
parameter    ap_ST_fsm_state59 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] size;
input  [31:0] dim;
input  [31:0] threshold;
output   data0_req_din;
input   data0_req_full_n;
output   data0_req_write;
input   data0_rsp_empty_n;
output   data0_rsp_read;
output  [31:0] data0_address;
input  [31:0] data0_datain;
output  [31:0] data0_dataout;
output  [31:0] data0_size;
output   data1_req_din;
input   data1_req_full_n;
output   data1_req_write;
input   data1_rsp_empty_n;
output   data1_rsp_read;
output  [31:0] data1_address;
input  [31:0] data1_datain;
output  [31:0] data1_dataout;
output  [31:0] data1_size;
output   data2_req_din;
input   data2_req_full_n;
output   data2_req_write;
input   data2_rsp_empty_n;
output   data2_rsp_read;
output  [31:0] data2_address;
input  [31:0] data2_datain;
output  [31:0] data2_dataout;
output  [31:0] data2_size;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data0_req_write;
reg data0_rsp_read;
reg data1_req_write;
reg data1_rsp_read;
reg data2_req_din;
reg data2_req_write;

(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] i_reg_116;
wire   [31:0] grp_fu_163_p2;
reg   [31:0] reg_172;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_enable_reg_pp0_iter8;
reg   [0:0] tmp_s_reg_480;
reg    ap_block_state22_pp0_stage3_iter0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state26_pp0_stage3_iter1;
wire    ap_block_state30_pp0_stage3_iter2;
wire    ap_block_state34_pp0_stage3_iter3;
wire    ap_block_state38_pp0_stage3_iter4;
wire    ap_block_state42_pp0_stage3_iter5;
wire    ap_block_state46_pp0_stage3_iter6;
wire    ap_block_state50_pp0_stage3_iter7;
wire    ap_block_state54_pp0_stage3_iter8;
reg   [0:0] tmp_s_reg_480_pp0_iter9_reg;
reg    ap_block_state58_pp0_stage3_iter9;
reg    ap_enable_reg_pp0_iter9;
reg    ap_block_pp0_stage3_11001;
reg   [0:0] tmp_s_reg_480_pp0_iter8_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state19_pp0_stage0_iter0;
reg    ap_block_state23_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state27_pp0_stage0_iter2;
wire    ap_block_state31_pp0_stage0_iter3;
wire    ap_block_state35_pp0_stage0_iter4;
wire    ap_block_state39_pp0_stage0_iter5;
wire    ap_block_state43_pp0_stage0_iter6;
wire    ap_block_state47_pp0_stage0_iter7;
wire    ap_block_state51_pp0_stage0_iter8;
reg    ap_block_state55_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state20_pp0_stage1_iter0;
reg   [0:0] tmp_s_reg_480_pp0_iter1_reg;
reg    ap_block_state24_pp0_stage1_iter1;
wire    ap_block_state28_pp0_stage1_iter2;
wire    ap_block_state32_pp0_stage1_iter3;
wire    ap_block_state36_pp0_stage1_iter4;
wire    ap_block_state40_pp0_stage1_iter5;
wire    ap_block_state44_pp0_stage1_iter6;
wire    ap_block_state48_pp0_stage1_iter7;
wire    ap_block_state52_pp0_stage1_iter8;
reg    ap_block_state56_pp0_stage1_iter9;
reg    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state21_pp0_stage2_iter0;
reg    ap_block_state25_pp0_stage2_iter1;
wire    ap_block_state29_pp0_stage2_iter2;
wire    ap_block_state33_pp0_stage2_iter3;
wire    ap_block_state37_pp0_stage2_iter4;
wire    ap_block_state41_pp0_stage2_iter5;
wire    ap_block_state45_pp0_stage2_iter6;
wire    ap_block_state49_pp0_stage2_iter7;
wire    ap_block_state53_pp0_stage2_iter8;
reg    ap_block_state57_pp0_stage2_iter9;
reg    ap_block_pp0_stage2_11001;
reg   [31:0] data0_read_reg_400;
wire    ap_CS_fsm_state3;
reg   [31:0] data0_read_1_reg_405;
wire    ap_CS_fsm_state4;
reg   [31:0] data0_read_2_reg_410;
wire    ap_CS_fsm_state5;
reg   [31:0] data0_read_3_reg_415;
wire    ap_CS_fsm_state6;
reg   [31:0] data0_read_4_reg_420;
wire    ap_CS_fsm_state7;
reg   [31:0] data0_read_5_reg_425;
wire    ap_CS_fsm_state8;
reg   [31:0] data0_read_6_reg_430;
wire    ap_CS_fsm_state9;
reg   [31:0] data0_read_7_reg_435;
wire    ap_CS_fsm_state10;
reg   [31:0] data0_read_8_reg_440;
wire    ap_CS_fsm_state11;
reg   [31:0] data0_read_9_reg_445;
wire    ap_CS_fsm_state12;
reg   [31:0] data0_read_10_reg_450;
wire    ap_CS_fsm_state13;
reg   [31:0] data0_read_11_reg_455;
wire    ap_CS_fsm_state14;
reg   [31:0] data0_read_12_reg_460;
wire    ap_CS_fsm_state15;
reg   [31:0] data0_read_13_reg_465;
wire    ap_CS_fsm_state16;
reg   [31:0] data0_read_14_reg_470;
wire    ap_CS_fsm_state17;
reg   [31:0] data0_read_15_reg_475;
wire    ap_CS_fsm_state18;
wire   [0:0] tmp_s_fu_177_p2;
reg   [0:0] tmp_s_reg_480_pp0_iter2_reg;
reg   [0:0] tmp_s_reg_480_pp0_iter3_reg;
reg   [0:0] tmp_s_reg_480_pp0_iter4_reg;
reg   [0:0] tmp_s_reg_480_pp0_iter5_reg;
reg   [0:0] tmp_s_reg_480_pp0_iter6_reg;
reg   [0:0] tmp_s_reg_480_pp0_iter7_reg;
wire   [9:0] i_1_fu_183_p2;
reg   [9:0] i_1_reg_484;
wire   [11:0] tmp_1_fu_189_p3;
reg   [11:0] tmp_1_reg_489;
reg   [31:0] data2_addr_reg_500;
reg   [31:0] data2_addr_reg_500_pp0_iter1_reg;
reg   [31:0] data2_addr_reg_500_pp0_iter2_reg;
reg   [31:0] data2_addr_reg_500_pp0_iter3_reg;
reg   [31:0] data2_addr_reg_500_pp0_iter4_reg;
reg   [31:0] data2_addr_reg_500_pp0_iter5_reg;
reg   [31:0] data2_addr_reg_500_pp0_iter6_reg;
reg   [31:0] data2_addr_reg_500_pp0_iter7_reg;
reg   [31:0] data2_addr_reg_500_pp0_iter8_reg;
reg   [31:0] data1_addr_read_reg_505;
reg   [31:0] data1_addr_read_1_reg_513;
reg   [31:0] data1_addr_read_2_reg_521;
reg   [31:0] data1_addr_read_3_reg_529;
wire   [31:0] grp_fu_147_p2;
reg   [31:0] tmp_4_reg_537;
wire   [31:0] grp_fu_151_p2;
reg   [31:0] tmp_34_1_reg_542;
wire   [31:0] grp_fu_155_p2;
reg   [31:0] tmp_34_2_reg_547;
wire   [31:0] grp_fu_159_p2;
reg   [31:0] tmp_34_3_reg_552;
reg   [31:0] tmp_34_0_1_reg_557;
reg    ap_enable_reg_pp0_iter2;
reg   [31:0] tmp_34_0_1_reg_557_pp0_iter3_reg;
reg   [31:0] tmp_34_1_1_reg_562;
reg   [31:0] tmp_34_1_1_reg_562_pp0_iter3_reg;
reg   [31:0] tmp_34_2_1_reg_567;
reg   [31:0] tmp_34_2_1_reg_567_pp0_iter3_reg;
reg   [31:0] tmp_34_3_1_reg_572;
reg   [31:0] tmp_34_3_1_reg_572_pp0_iter3_reg;
reg   [31:0] tmp_34_0_2_reg_577;
reg   [31:0] tmp_34_0_2_reg_577_pp0_iter3_reg;
reg   [31:0] tmp_34_0_2_reg_577_pp0_iter4_reg;
reg   [31:0] tmp_34_1_2_reg_582;
reg   [31:0] tmp_34_1_2_reg_582_pp0_iter3_reg;
reg   [31:0] tmp_34_1_2_reg_582_pp0_iter4_reg;
reg   [31:0] tmp_34_2_2_reg_587;
reg   [31:0] tmp_34_2_2_reg_587_pp0_iter3_reg;
reg   [31:0] tmp_34_2_2_reg_587_pp0_iter4_reg;
reg   [31:0] tmp_34_3_2_reg_592;
reg   [31:0] tmp_34_3_2_reg_592_pp0_iter3_reg;
reg   [31:0] tmp_34_3_2_reg_592_pp0_iter4_reg;
reg   [31:0] tmp_34_0_3_reg_597;
reg   [31:0] tmp_34_0_3_reg_597_pp0_iter3_reg;
reg   [31:0] tmp_34_0_3_reg_597_pp0_iter4_reg;
reg   [31:0] tmp_34_0_3_reg_597_pp0_iter5_reg;
reg   [31:0] tmp_34_1_3_reg_602;
reg   [31:0] tmp_34_1_3_reg_602_pp0_iter3_reg;
reg   [31:0] tmp_34_1_3_reg_602_pp0_iter4_reg;
reg   [31:0] tmp_34_1_3_reg_602_pp0_iter5_reg;
reg   [31:0] tmp_34_2_3_reg_607;
reg   [31:0] tmp_34_2_3_reg_607_pp0_iter3_reg;
reg   [31:0] tmp_34_2_3_reg_607_pp0_iter4_reg;
reg   [31:0] tmp_34_2_3_reg_607_pp0_iter5_reg;
reg   [31:0] tmp_34_3_3_reg_612;
reg   [31:0] tmp_34_3_3_reg_612_pp0_iter3_reg;
reg   [31:0] tmp_34_3_3_reg_612_pp0_iter4_reg;
reg   [31:0] tmp_34_3_3_reg_612_pp0_iter5_reg;
wire   [31:0] grp_fu_127_p2;
reg   [31:0] tmp_6_reg_617;
reg    ap_enable_reg_pp0_iter3;
wire   [31:0] grp_fu_132_p2;
reg   [31:0] tmp_35_1_reg_622;
wire   [31:0] grp_fu_137_p2;
reg   [31:0] tmp_35_2_reg_627;
wire   [31:0] grp_fu_142_p2;
reg   [31:0] tmp_35_3_reg_632;
reg   [31:0] tmp_35_0_1_reg_637;
reg    ap_enable_reg_pp0_iter4;
reg   [31:0] tmp_35_1_1_reg_642;
reg   [31:0] tmp_35_2_1_reg_647;
reg   [31:0] tmp_35_3_1_reg_652;
reg   [31:0] tmp_35_0_2_reg_657;
reg    ap_enable_reg_pp0_iter5;
reg   [31:0] tmp_35_1_2_reg_662;
reg   [31:0] tmp_35_2_2_reg_667;
reg   [31:0] tmp_35_3_2_reg_672;
reg   [31:0] tmp_35_0_3_reg_677;
reg    ap_enable_reg_pp0_iter6;
reg   [31:0] tmp_35_0_3_reg_677_pp0_iter7_reg;
reg   [31:0] tmp_35_1_3_reg_684;
reg   [31:0] tmp_35_1_3_reg_684_pp0_iter7_reg;
reg   [31:0] tmp_35_2_3_reg_691;
reg   [31:0] tmp_35_2_3_reg_691_pp0_iter7_reg;
reg   [31:0] tmp_35_3_3_reg_698;
reg   [31:0] tmp_35_3_3_reg_698_pp0_iter7_reg;
wire   [0:0] grp_fu_167_p2;
reg   [0:0] tmp_10_reg_705;
reg    ap_enable_reg_pp0_iter7;
wire   [0:0] tmp_27_fu_294_p2;
reg   [0:0] tmp_27_reg_710;
reg   [0:0] tmp_20_reg_715;
wire   [0:0] tmp_28_fu_381_p2;
reg   [0:0] tmp_28_reg_720;
wire   [31:0] tmp_5_fu_391_p3;
reg   [31:0] tmp_5_reg_725;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state19;
reg    ap_block_pp0_stage3_subdone;
reg   [9:0] ap_phi_mux_i_phi_fu_120_p4;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_2_fu_197_p1;
wire    ap_block_pp0_stage1;
reg   [31:0] grp_fu_127_p0;
reg   [31:0] grp_fu_127_p1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
reg   [31:0] grp_fu_132_p0;
reg   [31:0] grp_fu_132_p1;
reg   [31:0] grp_fu_137_p0;
reg   [31:0] grp_fu_137_p1;
reg   [31:0] grp_fu_142_p0;
reg   [31:0] grp_fu_142_p1;
reg   [31:0] grp_fu_147_p0;
reg   [31:0] grp_fu_147_p1;
reg   [31:0] grp_fu_151_p0;
reg   [31:0] grp_fu_151_p1;
reg   [31:0] grp_fu_155_p0;
reg   [31:0] grp_fu_155_p1;
reg   [31:0] grp_fu_159_p0;
reg   [31:0] grp_fu_159_p1;
reg   [31:0] grp_fu_163_p0;
reg   [31:0] grp_fu_163_p1;
reg   [31:0] grp_fu_167_p0;
wire   [31:0] tmp_35_0_3_to_int_fu_213_p1;
wire   [7:0] tmp_8_fu_216_p4;
wire   [22:0] tmp_9_fu_226_p1;
wire   [0:0] notrhs_fu_236_p2;
wire   [0:0] notlhs_fu_230_p2;
wire   [0:0] tmp_3_fu_242_p2;
wire   [31:0] tmp_35_1_3_to_int_fu_253_p1;
wire   [7:0] tmp_12_fu_256_p4;
wire   [22:0] tmp_13_fu_266_p1;
wire   [0:0] notrhs6_fu_276_p2;
wire   [0:0] notlhs5_fu_270_p2;
wire   [0:0] tmp_14_fu_282_p2;
wire   [0:0] tmp_16_fu_288_p2;
wire   [0:0] tmp_11_fu_248_p2;
wire   [31:0] tmp_35_2_3_to_int_fu_300_p1;
wire   [7:0] tmp_17_fu_303_p4;
wire   [22:0] tmp_18_fu_313_p1;
wire   [0:0] notrhs8_fu_323_p2;
wire   [0:0] notlhs7_fu_317_p2;
wire   [0:0] tmp_19_fu_329_p2;
wire   [31:0] tmp_35_3_3_to_int_fu_340_p1;
wire   [7:0] tmp_22_fu_343_p4;
wire   [22:0] tmp_23_fu_353_p1;
wire   [0:0] notrhs1_fu_363_p2;
wire   [0:0] notlhs9_fu_357_p2;
wire   [0:0] tmp_24_fu_369_p2;
wire   [0:0] tmp_26_fu_375_p2;
wire   [0:0] tmp_21_fu_335_p2;
wire   [0:0] tmp_29_fu_387_p2;
reg    grp_fu_127_ce;
reg    grp_fu_132_ce;
reg    grp_fu_137_ce;
reg    grp_fu_142_ce;
reg    grp_fu_147_ce;
reg    grp_fu_151_ce;
reg    grp_fu_155_ce;
reg    grp_fu_159_ce;
reg    grp_fu_163_ce;
reg    ap_block_pp0_stage0_00001;
reg    ap_block_pp0_stage1_00001;
reg    ap_block_pp0_stage2_00001;
reg    ap_block_pp0_stage3_00001;
wire    ap_CS_fsm_state59;
reg   [22:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 23'd1;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
end

myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_127_p0),
    .din1(grp_fu_127_p1),
    .ce(grp_fu_127_ce),
    .dout(grp_fu_127_p2)
);

myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_132_p0),
    .din1(grp_fu_132_p1),
    .ce(grp_fu_132_ce),
    .dout(grp_fu_132_p2)
);

myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_137_p0),
    .din1(grp_fu_137_p1),
    .ce(grp_fu_137_ce),
    .dout(grp_fu_137_p2)
);

myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fadd_32ns_32ns_32_5_full_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_142_p0),
    .din1(grp_fu_142_p1),
    .ce(grp_fu_142_ce),
    .dout(grp_fu_142_p2)
);

myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_147_p0),
    .din1(grp_fu_147_p1),
    .ce(grp_fu_147_ce),
    .dout(grp_fu_147_p2)
);

myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_151_p0),
    .din1(grp_fu_151_p1),
    .ce(grp_fu_151_ce),
    .dout(grp_fu_151_p2)
);

myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_155_p0),
    .din1(grp_fu_155_p1),
    .ce(grp_fu_155_ce),
    .dout(grp_fu_155_p2)
);

myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_159_p0),
    .din1(grp_fu_159_p1),
    .ce(grp_fu_159_ce),
    .dout(grp_fu_159_p2)
);

myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
myFuncAccel_fmul_32ns_32ns_32_4_max_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_163_p0),
    .din1(grp_fu_163_p1),
    .ce(grp_fu_163_ce),
    .dout(grp_fu_163_p2)
);

myFuncAccel_fcmp_32ns_32ns_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
myFuncAccel_fcmp_32ns_32ns_1_1_1_U10(
    .din0(grp_fu_167_p0),
    .din1(32'd1120403456),
    .opcode(5'd5),
    .dout(grp_fu_167_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state19) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end else if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
            ap_enable_reg_pp0_iter9 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        i_reg_116 <= 10'd0;
    end else if (((tmp_s_reg_480 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_reg_116 <= i_1_reg_484;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        data0_read_10_reg_450 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        data0_read_11_reg_455 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        data0_read_12_reg_460 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        data0_read_13_reg_465 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        data0_read_14_reg_470 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        data0_read_15_reg_475 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        data0_read_1_reg_405 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        data0_read_2_reg_410 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        data0_read_3_reg_415 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        data0_read_4_reg_420 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        data0_read_5_reg_425 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        data0_read_6_reg_430 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        data0_read_7_reg_435 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        data0_read_8_reg_440 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        data0_read_9_reg_445 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data0_read_reg_400 <= data0_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data1_addr_read_1_reg_513 <= data1_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        data1_addr_read_2_reg_521 <= data1_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        data1_addr_read_3_reg_529 <= data1_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        data1_addr_read_reg_505 <= data1_datain;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        data2_addr_reg_500[11 : 2] <= tmp_2_fu_197_p1[11 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        data2_addr_reg_500_pp0_iter1_reg[11 : 2] <= data2_addr_reg_500[11 : 2];
        data2_addr_reg_500_pp0_iter2_reg[11 : 2] <= data2_addr_reg_500_pp0_iter1_reg[11 : 2];
        data2_addr_reg_500_pp0_iter3_reg[11 : 2] <= data2_addr_reg_500_pp0_iter2_reg[11 : 2];
        data2_addr_reg_500_pp0_iter4_reg[11 : 2] <= data2_addr_reg_500_pp0_iter3_reg[11 : 2];
        data2_addr_reg_500_pp0_iter5_reg[11 : 2] <= data2_addr_reg_500_pp0_iter4_reg[11 : 2];
        data2_addr_reg_500_pp0_iter6_reg[11 : 2] <= data2_addr_reg_500_pp0_iter5_reg[11 : 2];
        data2_addr_reg_500_pp0_iter7_reg[11 : 2] <= data2_addr_reg_500_pp0_iter6_reg[11 : 2];
        data2_addr_reg_500_pp0_iter8_reg[11 : 2] <= data2_addr_reg_500_pp0_iter7_reg[11 : 2];
        tmp_34_0_2_reg_577_pp0_iter3_reg <= tmp_34_0_2_reg_577;
        tmp_34_0_2_reg_577_pp0_iter4_reg <= tmp_34_0_2_reg_577_pp0_iter3_reg;
        tmp_34_1_2_reg_582_pp0_iter3_reg <= tmp_34_1_2_reg_582;
        tmp_34_1_2_reg_582_pp0_iter4_reg <= tmp_34_1_2_reg_582_pp0_iter3_reg;
        tmp_34_2_2_reg_587_pp0_iter3_reg <= tmp_34_2_2_reg_587;
        tmp_34_2_2_reg_587_pp0_iter4_reg <= tmp_34_2_2_reg_587_pp0_iter3_reg;
        tmp_34_3_2_reg_592_pp0_iter3_reg <= tmp_34_3_2_reg_592;
        tmp_34_3_2_reg_592_pp0_iter4_reg <= tmp_34_3_2_reg_592_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_1_reg_484 <= i_1_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        reg_172 <= grp_fu_163_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter6_reg == 1'd0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_10_reg_705 <= grp_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_177_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_1_reg_489[11 : 2] <= tmp_1_fu_189_p3[11 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_20_reg_715 <= grp_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_27_reg_710 <= tmp_27_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        tmp_28_reg_720 <= tmp_28_fu_381_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_34_0_1_reg_557 <= grp_fu_147_p2;
        tmp_34_1_1_reg_562 <= grp_fu_151_p2;
        tmp_34_2_1_reg_567 <= grp_fu_155_p2;
        tmp_34_3_1_reg_572 <= grp_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_34_0_1_reg_557_pp0_iter3_reg <= tmp_34_0_1_reg_557;
        tmp_34_1_1_reg_562_pp0_iter3_reg <= tmp_34_1_1_reg_562;
        tmp_34_2_1_reg_567_pp0_iter3_reg <= tmp_34_2_1_reg_567;
        tmp_34_3_1_reg_572_pp0_iter3_reg <= tmp_34_3_1_reg_572;
        tmp_s_reg_480 <= tmp_s_fu_177_p2;
        tmp_s_reg_480_pp0_iter1_reg <= tmp_s_reg_480;
        tmp_s_reg_480_pp0_iter2_reg <= tmp_s_reg_480_pp0_iter1_reg;
        tmp_s_reg_480_pp0_iter3_reg <= tmp_s_reg_480_pp0_iter2_reg;
        tmp_s_reg_480_pp0_iter4_reg <= tmp_s_reg_480_pp0_iter3_reg;
        tmp_s_reg_480_pp0_iter5_reg <= tmp_s_reg_480_pp0_iter4_reg;
        tmp_s_reg_480_pp0_iter6_reg <= tmp_s_reg_480_pp0_iter5_reg;
        tmp_s_reg_480_pp0_iter7_reg <= tmp_s_reg_480_pp0_iter6_reg;
        tmp_s_reg_480_pp0_iter8_reg <= tmp_s_reg_480_pp0_iter7_reg;
        tmp_s_reg_480_pp0_iter9_reg <= tmp_s_reg_480_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_34_0_2_reg_577 <= grp_fu_147_p2;
        tmp_34_1_2_reg_582 <= grp_fu_151_p2;
        tmp_34_2_2_reg_587 <= grp_fu_155_p2;
        tmp_34_3_2_reg_592 <= grp_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_34_0_3_reg_597 <= grp_fu_147_p2;
        tmp_34_1_3_reg_602 <= grp_fu_151_p2;
        tmp_34_2_3_reg_607 <= grp_fu_155_p2;
        tmp_34_3_3_reg_612 <= grp_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_34_0_3_reg_597_pp0_iter3_reg <= tmp_34_0_3_reg_597;
        tmp_34_0_3_reg_597_pp0_iter4_reg <= tmp_34_0_3_reg_597_pp0_iter3_reg;
        tmp_34_0_3_reg_597_pp0_iter5_reg <= tmp_34_0_3_reg_597_pp0_iter4_reg;
        tmp_34_1_3_reg_602_pp0_iter3_reg <= tmp_34_1_3_reg_602;
        tmp_34_1_3_reg_602_pp0_iter4_reg <= tmp_34_1_3_reg_602_pp0_iter3_reg;
        tmp_34_1_3_reg_602_pp0_iter5_reg <= tmp_34_1_3_reg_602_pp0_iter4_reg;
        tmp_34_2_3_reg_607_pp0_iter3_reg <= tmp_34_2_3_reg_607;
        tmp_34_2_3_reg_607_pp0_iter4_reg <= tmp_34_2_3_reg_607_pp0_iter3_reg;
        tmp_34_2_3_reg_607_pp0_iter5_reg <= tmp_34_2_3_reg_607_pp0_iter4_reg;
        tmp_34_3_3_reg_612_pp0_iter3_reg <= tmp_34_3_3_reg_612;
        tmp_34_3_3_reg_612_pp0_iter4_reg <= tmp_34_3_3_reg_612_pp0_iter3_reg;
        tmp_34_3_3_reg_612_pp0_iter5_reg <= tmp_34_3_3_reg_612_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        tmp_34_1_reg_542 <= grp_fu_151_p2;
        tmp_34_2_reg_547 <= grp_fu_155_p2;
        tmp_34_3_reg_552 <= grp_fu_159_p2;
        tmp_4_reg_537 <= grp_fu_147_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_35_0_1_reg_637 <= grp_fu_127_p2;
        tmp_35_1_1_reg_642 <= grp_fu_132_p2;
        tmp_35_2_1_reg_647 <= grp_fu_137_p2;
        tmp_35_3_1_reg_652 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_35_0_2_reg_657 <= grp_fu_127_p2;
        tmp_35_1_2_reg_662 <= grp_fu_132_p2;
        tmp_35_2_2_reg_667 <= grp_fu_137_p2;
        tmp_35_3_2_reg_672 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        tmp_35_0_3_reg_677 <= grp_fu_127_p2;
        tmp_35_1_3_reg_684 <= grp_fu_132_p2;
        tmp_35_2_3_reg_691 <= grp_fu_137_p2;
        tmp_35_3_3_reg_698 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        tmp_35_0_3_reg_677_pp0_iter7_reg <= tmp_35_0_3_reg_677;
        tmp_35_1_3_reg_684_pp0_iter7_reg <= tmp_35_1_3_reg_684;
        tmp_35_2_3_reg_691_pp0_iter7_reg <= tmp_35_2_3_reg_691;
        tmp_35_3_3_reg_698_pp0_iter7_reg <= tmp_35_3_3_reg_698;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_35_1_reg_622 <= grp_fu_132_p2;
        tmp_35_2_reg_627 <= grp_fu_137_p2;
        tmp_35_3_reg_632 <= grp_fu_142_p2;
        tmp_6_reg_617 <= grp_fu_127_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_480_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_5_reg_725[29 : 23] <= tmp_5_fu_391_p3[29 : 23];
    end
end

always @ (*) begin
    if ((tmp_s_fu_177_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state19 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state19 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_reg_480 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_phi_fu_120_p4 = i_1_reg_484;
    end else begin
        ap_phi_mux_i_phi_fu_120_p4 = i_reg_116;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        data0_req_write = 1'b1;
    end else begin
        data0_req_write = 1'b0;
    end
end

always @ (*) begin
    if ((((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        data0_rsp_read = 1'b1;
    end else begin
        data0_rsp_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_s_reg_480 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        data1_req_write = 1'b1;
    end else begin
        data1_req_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_480 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001)) | ((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((tmp_s_reg_480 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        data1_rsp_read = 1'b1;
    end else begin
        data1_rsp_read = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001)) | ((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        data2_req_din = 1'b1;
    end else begin
        data2_req_din = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001)) | ((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        data2_req_write = 1'b1;
    end else begin
        data2_req_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_127_ce = 1'b1;
    end else begin
        grp_fu_127_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_127_p0 = tmp_35_0_2_reg_657;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_127_p0 = tmp_35_0_1_reg_637;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_127_p0 = tmp_6_reg_617;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_127_p0 = tmp_4_reg_537;
    end else begin
        grp_fu_127_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_127_p1 = tmp_34_0_3_reg_597_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_127_p1 = tmp_34_0_2_reg_577_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_127_p1 = tmp_34_0_1_reg_557_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_127_p1 = 32'd0;
    end else begin
        grp_fu_127_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_132_ce = 1'b1;
    end else begin
        grp_fu_132_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_132_p0 = tmp_35_1_2_reg_662;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_132_p0 = tmp_35_1_1_reg_642;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_132_p0 = tmp_35_1_reg_622;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_132_p0 = tmp_34_1_reg_542;
    end else begin
        grp_fu_132_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_132_p1 = tmp_34_1_3_reg_602_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_132_p1 = tmp_34_1_2_reg_582_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_132_p1 = tmp_34_1_1_reg_562_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_132_p1 = 32'd0;
    end else begin
        grp_fu_132_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_137_ce = 1'b1;
    end else begin
        grp_fu_137_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_137_p0 = tmp_35_2_2_reg_667;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_137_p0 = tmp_35_2_1_reg_647;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_137_p0 = tmp_35_2_reg_627;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_137_p0 = tmp_34_2_reg_547;
    end else begin
        grp_fu_137_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_137_p1 = tmp_34_2_3_reg_607_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_137_p1 = tmp_34_2_2_reg_587_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_137_p1 = tmp_34_2_1_reg_567_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_137_p1 = 32'd0;
    end else begin
        grp_fu_137_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_142_ce = 1'b1;
    end else begin
        grp_fu_142_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_142_p0 = tmp_35_3_2_reg_672;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_142_p0 = tmp_35_3_1_reg_652;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_142_p0 = tmp_35_3_reg_632;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_142_p0 = tmp_34_3_reg_552;
    end else begin
        grp_fu_142_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_142_p1 = tmp_34_3_3_reg_612_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_142_p1 = tmp_34_3_2_reg_592_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_142_p1 = tmp_34_3_1_reg_572_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_142_p1 = 32'd0;
    end else begin
        grp_fu_142_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_147_ce = 1'b1;
    end else begin
        grp_fu_147_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_147_p0 = data0_read_3_reg_415;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_147_p0 = data0_read_2_reg_410;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_147_p0 = data0_read_1_reg_405;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_147_p0 = data0_read_reg_400;
        end else begin
            grp_fu_147_p0 = 'bx;
        end
    end else begin
        grp_fu_147_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_147_p1 = data1_addr_read_3_reg_529;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_147_p1 = data1_addr_read_2_reg_521;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_147_p1 = data1_addr_read_1_reg_513;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_147_p1 = data1_addr_read_reg_505;
        end else begin
            grp_fu_147_p1 = 'bx;
        end
    end else begin
        grp_fu_147_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_151_ce = 1'b1;
    end else begin
        grp_fu_151_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_151_p0 = data0_read_7_reg_435;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_151_p0 = data0_read_6_reg_430;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_151_p0 = data0_read_5_reg_425;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_151_p0 = data0_read_4_reg_420;
        end else begin
            grp_fu_151_p0 = 'bx;
        end
    end else begin
        grp_fu_151_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_151_p1 = data1_addr_read_3_reg_529;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_151_p1 = data1_addr_read_2_reg_521;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_151_p1 = data1_addr_read_1_reg_513;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_151_p1 = data1_addr_read_reg_505;
        end else begin
            grp_fu_151_p1 = 'bx;
        end
    end else begin
        grp_fu_151_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_155_ce = 1'b1;
    end else begin
        grp_fu_155_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_155_p0 = data0_read_11_reg_455;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_155_p0 = data0_read_10_reg_450;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_155_p0 = data0_read_9_reg_445;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_155_p0 = data0_read_8_reg_440;
        end else begin
            grp_fu_155_p0 = 'bx;
        end
    end else begin
        grp_fu_155_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_155_p1 = data1_addr_read_3_reg_529;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_155_p1 = data1_addr_read_2_reg_521;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_155_p1 = data1_addr_read_1_reg_513;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_155_p1 = data1_addr_read_reg_505;
        end else begin
            grp_fu_155_p1 = 'bx;
        end
    end else begin
        grp_fu_155_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_159_ce = 1'b1;
    end else begin
        grp_fu_159_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_159_p0 = data0_read_15_reg_475;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_159_p0 = data0_read_14_reg_470;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_159_p0 = data0_read_13_reg_465;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_159_p0 = data0_read_12_reg_460;
        end else begin
            grp_fu_159_p0 = 'bx;
        end
    end else begin
        grp_fu_159_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_159_p1 = data1_addr_read_3_reg_529;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_159_p1 = data1_addr_read_2_reg_521;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_159_p1 = data1_addr_read_1_reg_513;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_159_p1 = data1_addr_read_reg_505;
        end else begin
            grp_fu_159_p1 = 'bx;
        end
    end else begin
        grp_fu_159_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_163_ce = 1'b1;
    end else begin
        grp_fu_163_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_163_p0 = tmp_35_3_3_reg_698_pp0_iter7_reg;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_163_p0 = tmp_35_2_3_reg_691_pp0_iter7_reg;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_163_p0 = tmp_35_1_3_reg_684_pp0_iter7_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_163_p0 = tmp_35_0_3_reg_677_pp0_iter7_reg;
        end else begin
            grp_fu_163_p0 = 'bx;
        end
    end else begin
        grp_fu_163_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_163_p1 = tmp_5_reg_725;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_163_p1 = tmp_5_fu_391_p3;
    end else begin
        grp_fu_163_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_167_p0 = tmp_35_3_3_reg_698;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_167_p0 = tmp_35_2_3_reg_691;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_167_p0 = tmp_35_1_3_reg_684;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_167_p0 = tmp_35_0_3_reg_677;
        end else begin
            grp_fu_167_p0 = 'bx;
        end
    end else begin
        grp_fu_167_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((data0_rsp_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (tmp_s_fu_177_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (tmp_s_fu_177_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((~((ap_enable_reg_pp0_iter8 == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter9 == 1'b1)) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter8 == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = (((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_00001 = (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_00001 = (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_00001 = (((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)));
end

assign ap_block_state19_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22_pp0_stage3_iter0 = ((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state23_pp0_stage0_iter1 = ((tmp_s_reg_480 == 1'd0) & (data1_rsp_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state24_pp0_stage1_iter1 = ((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state25_pp0_stage2_iter1 = ((tmp_s_reg_480_pp0_iter1_reg == 1'd0) & (data1_rsp_empty_n == 1'b0));
end

assign ap_block_state26_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage3_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state55_pp0_stage0_iter9 = ((tmp_s_reg_480_pp0_iter8_reg == 1'd0) & (data2_req_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state56_pp0_stage1_iter9 = ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state57_pp0_stage2_iter9 = ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state58_pp0_stage3_iter9 = ((tmp_s_reg_480_pp0_iter9_reg == 1'd0) & (data2_req_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign data0_address = 32'd0;

assign data0_dataout = 32'd0;

assign data0_req_din = 1'b0;

assign data0_size = 32'd16;

assign data1_address = tmp_2_fu_197_p1;

assign data1_dataout = 32'd0;

assign data1_req_din = 1'b0;

assign data1_size = 32'd4;

assign data2_address = data2_addr_reg_500_pp0_iter8_reg;

assign data2_dataout = reg_172;

assign data2_rsp_read = 1'b0;

assign data2_size = 32'd4;

assign i_1_fu_183_p2 = (ap_phi_mux_i_phi_fu_120_p4 + 10'd1);

assign notlhs5_fu_270_p2 = ((tmp_12_fu_256_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs7_fu_317_p2 = ((tmp_17_fu_303_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs9_fu_357_p2 = ((tmp_22_fu_343_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs_fu_230_p2 = ((tmp_8_fu_216_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs1_fu_363_p2 = ((tmp_23_fu_353_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs6_fu_276_p2 = ((tmp_13_fu_266_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs8_fu_323_p2 = ((tmp_18_fu_313_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_236_p2 = ((tmp_9_fu_226_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_248_p2 = (tmp_3_fu_242_p2 & tmp_10_reg_705);

assign tmp_12_fu_256_p4 = {{tmp_35_1_3_to_int_fu_253_p1[30:23]}};

assign tmp_13_fu_266_p1 = tmp_35_1_3_to_int_fu_253_p1[22:0];

assign tmp_14_fu_282_p2 = (notrhs6_fu_276_p2 | notlhs5_fu_270_p2);

assign tmp_16_fu_288_p2 = (tmp_14_fu_282_p2 & grp_fu_167_p2);

assign tmp_17_fu_303_p4 = {{tmp_35_2_3_to_int_fu_300_p1[30:23]}};

assign tmp_18_fu_313_p1 = tmp_35_2_3_to_int_fu_300_p1[22:0];

assign tmp_19_fu_329_p2 = (notrhs8_fu_323_p2 | notlhs7_fu_317_p2);

assign tmp_1_fu_189_p3 = {{ap_phi_mux_i_phi_fu_120_p4}, {2'd0}};

assign tmp_21_fu_335_p2 = (tmp_20_reg_715 & tmp_19_fu_329_p2);

assign tmp_22_fu_343_p4 = {{tmp_35_3_3_to_int_fu_340_p1[30:23]}};

assign tmp_23_fu_353_p1 = tmp_35_3_3_to_int_fu_340_p1[22:0];

assign tmp_24_fu_369_p2 = (notrhs1_fu_363_p2 | notlhs9_fu_357_p2);

assign tmp_26_fu_375_p2 = (tmp_24_fu_369_p2 & grp_fu_167_p2);

assign tmp_27_fu_294_p2 = (tmp_16_fu_288_p2 | tmp_11_fu_248_p2);

assign tmp_28_fu_381_p2 = (tmp_26_fu_375_p2 | tmp_21_fu_335_p2);

assign tmp_29_fu_387_p2 = (tmp_28_reg_720 | tmp_27_reg_710);

assign tmp_2_fu_197_p1 = tmp_1_reg_489;

assign tmp_35_0_3_to_int_fu_213_p1 = tmp_35_0_3_reg_677;

assign tmp_35_1_3_to_int_fu_253_p1 = tmp_35_1_3_reg_684;

assign tmp_35_2_3_to_int_fu_300_p1 = tmp_35_2_3_reg_691;

assign tmp_35_3_3_to_int_fu_340_p1 = tmp_35_3_3_reg_698;

assign tmp_3_fu_242_p2 = (notrhs_fu_236_p2 | notlhs_fu_230_p2);

assign tmp_5_fu_391_p3 = ((tmp_29_fu_387_p2[0:0] === 1'b1) ? 32'd1065353216 : 32'd0);

assign tmp_8_fu_216_p4 = {{tmp_35_0_3_to_int_fu_213_p1[30:23]}};

assign tmp_9_fu_226_p1 = tmp_35_0_3_to_int_fu_213_p1[22:0];

assign tmp_s_fu_177_p2 = ((ap_phi_mux_i_phi_fu_120_p4 == 10'd1000) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_1_reg_489[1:0] <= 2'b00;
    data2_addr_reg_500[1:0] <= 2'b00;
    data2_addr_reg_500[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter1_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter1_reg[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter2_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter2_reg[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter3_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter3_reg[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter4_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter4_reg[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter5_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter5_reg[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter6_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter6_reg[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter7_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter7_reg[31:12] <= 20'b00000000000000000000;
    data2_addr_reg_500_pp0_iter8_reg[1:0] <= 2'b00;
    data2_addr_reg_500_pp0_iter8_reg[31:12] <= 20'b00000000000000000000;
    tmp_5_reg_725[22:0] <= 23'b00000000000000000000000;
    tmp_5_reg_725[31:30] <= 2'b00;
end

endmodule //myFuncAccel
